import { supabase, chatAction, getMutualFriends } from './supabase-client.js';
import { account } from './session.js';
import { element, actionButton, avatar, notify } from './ui.js';
import { dialog, confirmAction } from './context-menu.js';
import { awakenBattleIdentity } from './awakening.js';
import { classIdentity } from './battle-classes.js';
import { progressionCard } from './battle-progress.js';
import { goRoute, parseRoute, backRoute } from './router.js';
let active;
const rpc=(name,args={})=>chatAction(name,args);
function button(label,fn,style='quiet-button'){const b=actionButton(label,null,style);b.addEventListener('click',async()=>{if(b.disabled)return;b.disabled=true;try{await fn();}catch(error){notify(error.message||'Please retry.');}finally{if(b.isConnected)b.disabled=false;}});return b;}
function select(label,items,parent){const wrap=element('label','social-field',label),s=element('select');for(const [value,name]of items){const o=element('option','',name);o.value=value;s.append(o);}wrap.append(s);parent.append(wrap);return s;}
export async function openBattleHub(partyId){
 const current=await account;if(!current)return;if(active?.routeKey===(partyId||'arena')){active.load();return;}active?.close();
 const panel=dialog(partyId?'Your party':'KAIDRA / BATTLES','battle-hub-modal'),body=element('div','battle-hub');panel.card.append(body);panel.open();active=panel;panel.routeKey=partyId||'arena';panel.load=load;
 let generation=0,channel;
 async function load(){const version=++generation;body.setAttribute('aria-busy','true');try{if(partyId)await renderParty(partyId);else await renderHome();}catch(error){if(version===generation&&body.isConnected){body.replaceChildren(element('p','form-error',error.message||'Battles could not load.'),button('Reconnect',load));}}finally{body.removeAttribute('aria-busy');}}
 async function renderHome(){const [identity,history,stats,membership,invites,rivals]=await Promise.all([rpc('kaidra_battle_identity'),rpc('kaidra_combat_history'),supabase.from('battle_stats').select('*').eq('user_id',current.userId).maybeSingle(),supabase.from('rpg_party_members').select('*').eq('user_id',current.userId).maybeSingle(),supabase.from('rpg_party_invites').select('*').eq('user_id',current.userId).eq('status','pending'),supabase.from('battle_rivalries').select('*').order('last_at',{ascending:false}).limit(20)]);
 if(!body.isConnected)return;body.replaceChildren();const hero=element('section','battle-hub-hero');hero.append(element('small','eyebrow','YOUR BATTLE JOURNEY'),element('h2','',identity?'Shape your path.':'Discover your destiny.'),element('p','muted','Interactive class combat, friendly challenges and a party of your own. Your record stays private.'));if(identity)hero.append(classIdentity(identity));else hero.append(button('Begin class determination',async()=>{if(await awakenBattleIdentity())load();},'primary-button'));body.append(hero);
 if(identity){const actions=element('div','detail-actions');actions.append(button('Challenge a friend',async()=>{panel.close();document.dispatchEvent(new CustomEvent('kaidra:new-duel'));},'primary-button'));if(membership.data)actions.append(button('My party',()=>goRoute('party/'+membership.data.party_id)));else actions.append(button('Create party',createParty));body.append(actions,progressionCard(stats.data||{}));}
 if(membership.error||invites.error||rivals.error)body.append(element('p','muted','Party and rivalry features are awaiting their database update. Duels and progression remain available.'));
 for(const invitation of invites.data||[]){if(Date.parse(invitation.created_at)<Date.now()-7*86400000)continue;const card=element('article','battle-hub-row');card.append(element('strong','','A friend invited you to a party'),button('View invitation',()=>goRoute('party/'+invitation.party_id)));body.append(card);}
 const section=element('section','battle-hub-section');section.append(element('h3','','Your recent battles'));for(const battle of history.filter(b=>!['expired','cancelled','declined'].includes(b.status))){const card=element('article','battle-hub-row'),names=battle.fighters.filter(f=>f.id!==current.userId).map(f=>f.name).join(' + ');card.append(element('strong','',battle.context?.party_battle?'2v2 · '+battle.context.party_b_name:'vs '+names),element('small','muted',new Date(battle.created_at).toLocaleDateString()+' · '+battle.status));if(battle.own_reward!=null)card.append(element('small','',`+${battle.own_reward} XP`));card.append(button(battle.status==='active'?'Enter arena':'View battle',()=>goRoute('battle/'+battle.id)));section.append(card);}if(!history.some(b=>!['expired','cancelled','declined'].includes(b.status)))section.append(element('p','muted','Your first friendly duel starts with an invitation.'));body.append(section);
 const rs=element('section','battle-hub-section');rs.append(element('h3','','Rivalries'));const established=(rivals.data||[]).filter(r=>r.battles>=3);if(!established.length)rs.append(element('p','muted','Three meaningful matches create an opportunity to recognize a rivalry together.'));const opponentIds=established.filter(r=>r.kind==='duel').map(r=>r.side_a===current.userId?r.side_b:r.side_a);const rivalPeople=opponentIds.length?(await supabase.from('profiles').select('id,username,display_name').in('id',opponentIds)).data||[]:[];if(!body.isConnected)return;
 for(const rival of established){let side=current.userId;if(rival.kind==='party')side=membership.data?.party_id;const ownA=rival.side_a===side,recognized=ownA?rival.recognized_a:rival.recognized_b,otherRecognized=ownA?rival.recognized_b:rival.recognized_a,card=element('article','battle-hub-row');const opponentId=ownA?rival.side_b:rival.side_a,person=rivalPeople.find(p=>p.id===opponentId);const historical=history.find(b=>b.context?.party_a===opponentId||b.context?.party_b===opponentId),partyName=historical?.context?.party_a===opponentId?historical.context.party_a_name:historical?.context?.party_b_name;card.append(element('strong','',rival.kind==='party'?'vs '+(partyName||'Opposing party'):'vs '+(person?.display_name||person?.username||'Your rival')),element('p','muted',`${rival.battles} matches · ${ownA?rival.wins_a:rival.wins_b} wins · ${ownA?rival.wins_b:rival.wins_a} losses${rival.streak?' · '+rival.streak+' consecutive wins for the current leader':''}`),element('small','muted',recognized?(otherRecognized?'Mutually recognized':'Waiting for their recognition'):'Recognition is optional. No stat bonuses.'));if(!recognized)card.append(button('Recognize rivalry',async()=>{await rpc('kaidra_rivalry_recognize',{target_rivalry:rival.id});load();}));if(recognized&&otherRecognized&&rival.kind==='duel')card.append(button('Challenge rival',async()=>{const bid=await rpc('kaidra_rival_duel',{target_rivalry:rival.id,request_id:crypto.randomUUID()});goRoute('battle/'+bid);}));if(recognized&&otherRecognized&&rival.kind==='party'&&membership.data)card.append(button('Challenge rival party',async()=>{const own=await rpc('kaidra_party_state',{target_party:membership.data.party_id});await challengeParty(own,rival);}));rs.append(card);}body.append(rs);
 }
 async function createParty(){if(!await awakenBattleIdentity())return;const formPanel=dialog('Create your party','party-create-modal'),form=element('form','party-create-form'),label=element('label','social-field','Party name'),input=element('input');input.required=true;input.minLength=2;input.maxLength=40;input.placeholder='Give your party a name';label.append(input);form.append(element('p','muted','Up to four friends. Members join by invitation. Your party gets its own group chat.'),label);const emblem=select('Emblem',[['constellation','Constellation'],['eclipse','Eclipse'],['comet','Comet']],form),submit=actionButton('Create party',null,'primary-button'),error=element('p','form-error');submit.type='submit';form.append(error,submit);formPanel.card.append(form);formPanel.open();const requestId=crypto.randomUUID();form.addEventListener('submit',async e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;try{const id=await rpc('kaidra_party_create',{party_name:input.value.trim(),emblem:emblem.value,request_id:requestId});formPanel.close();goRoute('party/'+id);}catch(problem){error.textContent=problem.message;submit.disabled=false;}});}
 async function renderParty(id){const data=await rpc('kaidra_party_state',{target_party:id});if(!body.isConnected)return;const party=data.party,own=data.members.find(m=>m.id===current.userId),leader=party.leader_id===current.userId;body.replaceChildren();const header=element('section','battle-hub-hero'),sigil=element('span','party-sigil');sigil.dataset.emblem=party.emblem;sigil.setAttribute('aria-hidden','true');header.append(sigil,element('small','eyebrow','YOUR PARTY'),element('h2','',party.name),element('p','muted',`${data.members.length} / 4 members · Invitations only. Friends of the leader can find this party for challenges.`));body.append(header);
 const roster=element('div','party-roster');for(const member of data.members){const card=element('article','party-member');card.append(avatar({display_name:member.name,avatar_url:member.avatar_url}),element('strong','',member.name),element('small','muted',member.leader?'LEADER':'MEMBER'));const identity=classIdentity(member.identity,{compact:true});if(identity)card.append(identity);if(leader&&member.id!==current.userId){card.append(button('Transfer leadership',async()=>{if(await confirmAction('Transfer leadership?',`${member.name} will lead this party.`,'Transfer')){await rpc('kaidra_party_action',{target_party:id,action:'transfer',target_user:member.id});load();}}),button('Remove member',async()=>{if(await confirmAction('Remove member?',`${member.name} leaves the party and its group chat.`,'Remove')){await rpc('kaidra_party_action',{target_party:id,action:'remove',target_user:member.id});load();}}));}roster.append(card);}body.append(roster);
 const actions=element('div','detail-actions');if(!own&&data.own_invite?.status==='pending'){actions.append(button('Accept invitation',async()=>{if(!await awakenBattleIdentity())return;await rpc('kaidra_party_action',{target_party:id,action:'accept'});load();},'primary-button'),button('Decline',async()=>{await rpc('kaidra_party_action',{target_party:id,action:'decline'});goRoute('arena');}));}if(own){actions.append(button('Open party chat',()=>goRoute('inbox/'+party.conversation_id)));if(leader){if(data.members.length<4)actions.append(button('Invite a friend',async()=>{const friends=(await getMutualFriends(current.userId)).filter(f=>!data.members.some(m=>m.id===f.id));const invitePanel=dialog('Invite a friend','party-invite-modal');if(!friends.length)invitePanel.card.append(element('p','muted','Add a friend before inviting someone new.'));for(const friend of friends)invitePanel.card.append(button(friend.display_name||friend.username,async()=>{await rpc('kaidra_party_invite',{target_party:id,target_user:friend.id});invitePanel.close();notify('Invitation sent.');load();}));invitePanel.open();}));actions.append(button('Challenge another party',()=>challengeParty(data), 'primary-button'),button('Disband party',async()=>{if(await confirmAction('Disband this party?','The group chat remains as a normal group.','Disband')){await rpc('kaidra_party_action',{target_party:id,action:'disband'});goRoute('arena');}}));}else actions.append(button('Leave party',async()=>{if(await confirmAction('Leave your party?','You will also leave its group chat.','Leave')){await rpc('kaidra_party_action',{target_party:id,action:'leave'});goRoute('arena');}}));}actions.append(button('My battle journey',()=>goRoute('arena')));body.append(actions,element('p','muted','Each fighter must accept a 2v2 challenge and controls only their own character. Party membership never grants control over a teammate.'));
 }
 async function challengeParty(data,rival){const candidates=await rpc('kaidra_party_opponents'),eligible=candidates.filter(p=>p.members.length>=2&&(!rival||[rival.side_a,rival.side_b].includes(p.id)));if(data.party.leader_id!==current.userId)throw new Error('Only your party leader can propose a battle.');const mates=data.members.filter(m=>m.id!==current.userId);if(!mates.length||!eligible.length)throw new Error('Both parties need at least two awakened members. Add friends or invite a teammate first.');const chooser=dialog('Propose a friendly 2v2','party-challenge-modal'),form=element('form');form.append(element('p','muted','Choose your teammate and opposing party. Both leaders and both teammates must accept.'));const teammate=select('Your teammate',mates.map(m=>[m.id,m.name]),form),opponent=select('Opposing party',eligible.map(p=>[p.id,p.name]),form),theirWrap=element('div');form.append(theirWrap);let theirMate;function update(){theirWrap.replaceChildren();const p=eligible.find(p=>p.id===opponent.value);theirMate=select('Their teammate',p.members.filter(m=>m.id!==p.leader_id).map(m=>[m.id,m.name]),theirWrap);}update();opponent.addEventListener('change',update);const submit=actionButton('Send 2v2 challenge',null,'primary-button'),error=element('p','form-error');submit.type='submit';form.append(error,submit);chooser.card.append(form);chooser.open();const requestId=crypto.randomUUID();form.addEventListener('submit',async e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;try{const p=eligible.find(p=>p.id===opponent.value);const id=await rpc('kaidra_party_challenge',{target_party:p.id,own_teammate:teammate.value,opponents:[p.leader_id,theirMate.value],request_id:requestId,rivalry_id:rival?.id||null});chooser.close();goRoute('battle/'+id);}catch(problem){error.textContent=problem.message;submit.disabled=false;}});}
 const close=event=>{if(event.detail.id!==panel.id)return;document.removeEventListener('kaidra:modal-close',close);if(channel)supabase.removeChannel(channel);if(active===panel)active=null;const route=parseRoute(location.hash);if(route.view===(partyId?'party':'arena')&&(!partyId||route.id===partyId))backRoute('home');};document.addEventListener('kaidra:modal-close',close);
 await load();if(!panel.modal.isConnected)return;
 channel=supabase.channel('battle-hub:'+current.userId).on('postgres_changes',{event:'*',schema:'public',table:'rpg_party_invites',filter:'user_id=eq.'+current.userId},load);
 if(partyId)channel.on('postgres_changes',{event:'*',schema:'public',table:'rpg_party_members',filter:'party_id=eq.'+partyId},load).on('postgres_changes',{event:'*',schema:'public',table:'rpg_parties',filter:'id=eq.'+partyId},load);
 else channel.on('postgres_changes',{event:'*',schema:'public',table:'battle_rivalries'},load);
 channel.subscribe();
}
document.addEventListener('kaidra:route-change',event=>{if(['arena','party'].includes(event.detail.view))openBattleHub(event.detail.id);else active?.close();});
document.addEventListener('kaidra:party-rematch',async()=>{try{const current=await account;const {data,error}=await supabase.from('rpg_party_members').select('party_id').eq('user_id',current.userId).maybeSingle();if(error)throw error;goRoute(data?'party/'+data.party_id:'arena');notify('Your leader can propose a new 2v2 challenge. Every fighter must accept again.');}catch{notify('Your party could not load. Please retry.');}});
const entry=actionButton('Battles','spark','quiet-button battle-entry');entry.addEventListener('click',()=>goRoute('arena'));document.querySelector('#tab-home .page-heading')?.append(entry);
