import { supabase, chatAction } from './supabase-client.js';
import { account } from './session.js';
import { element, artwork, actionButton, closeModal, notify } from './ui.js';
import { dialog, confirmAction } from './context-menu.js';
import { goRoute, parseRoute, backRoute } from './router.js';
import { battleClasses, classEmblem, classIdentity } from './battle-classes.js';
import { awakenBattleIdentity } from './awakening.js';
import { progressionCard } from './battle-progress.js';
let arena;
const errors={NOT_YOUR_TURN:'It is another fighter’s turn.',STALE_TURN:'The turn changed. Your arena is syncing.',TURN_EXPIRED:'Time ran out. Your arena is syncing.',ABILITY_COOLDOWN:'This ability is still on cooldown.',INSUFFICIENT_RESOURCE:'You need more resource for that ability.',INVALID_TARGET:'Choose a living, eligible fighter.',BATTLE_NOT_ACTIVE:'This battle has ended.',ACCESS_DENIED:'You no longer have access to this battle.',IDEMPOTENCY_CONFLICT:'That action has already been submitted.'};
async function request(body){const {data,error}=await supabase.functions.invoke('combat-api',{body});let problem=data;if(error?.context?.json)try{problem=await error.context.clone().json();}catch{}if(error||data?.code)throw new Error(errors[problem?.code]||'Combat could not sync. Please retry.');return data;}
const btn=(text,fn,style='quiet-button')=>{const b=actionButton(text,null,style);b.addEventListener('click',fn);return b;};
function summary(e,data){const name=id=>data.fighters.find(f=>f.user_id===id)?.name||'Fighter';if(e.kind==='ability_used')return `${name(e.source)} used ${e.name}.`;if(e.kind==='damage')return `${name(e.target)} took ${e.amount} damage${e.blocked?' · '+e.blocked+' blocked':''}.`;if(e.kind==='heal')return `${name(e.target)} recovered ${e.amount} HP.`;if(e.kind==='fighter_defeated')return `${name(e.target)} was defeated${e.surrender?' · conceded':e.timeouts?' · repeated timeouts':''}.`;if(e.kind==='status_applied')return `${name(e.target)} · ${e.status.replaceAll('_',' ')}${e.duration?' for '+e.duration+' own turns':''}.`;if(e.kind==='turn_timeout')return `${name(e.source)} timed out and guarded.`;if(e.kind==='intercept')return `${name(e.source)} intercepted an attack for ${name(e.target)}.`;if(e.kind==='pressure')return `Late-battle pressure dealt ${e.amount} to ${name(e.target)}.`;return '';}
export async function openCombat(id){
 if(arena?.id===id){arena.load();return;}
 arena?.close();closeModal('content-detail-modal');const current=await account;if(!current)return;
 const panel=dialog('KAIDRA / BATTLE','combat-arena-modal'),body=element('div','combat-arena');panel.card.append(body);panel.open();let data,busy=false,selection=null,pendingIntent=null,loading=null,revision=-1,clockOffset=0,channel,timer,poll,triedTimeout=-1,connected=false,visibility;
 const state=arena={id,load,close:()=>panel.close()};panel.modal.dataset.battleId=id;body.append(element('p','muted','Entering the arena…'));
 const errorNode=element('p','combat-error');errorNode.setAttribute('role','alert');
 async function load(){if(loading)return loading;loading=(async()=>{try{update(await request({action:'state',battle_id:id}));}catch(error){if(panel.modal.isConnected){errorNode.textContent=error.message;if(!errorNode.isConnected)body.append(errorNode,btn('Reconnect',load));}}finally{loading=null;}})();return loading;}
 function update(next){if(!panel.modal.isConnected||!next?.combat)return;clockOffset=Date.parse(next.server_now)-Date.now();if(next.combat.revision<revision)return;const previous=data;data=next;panel.modal.dataset.conversationId=data.battle.conversation_id;if(data.combat.revision!==revision){revision=data.combat.revision;selection=null;if(pendingIntent&&data.events.some(e=>e.request_id===pendingIntent.request_id)){pendingIntent=null;busy=false;}render(previous);}else if(!busy&&data.combat.phase==='waiting'&&JSON.stringify(previous?.fighters.map(f=>f.ready))!==JSON.stringify(data.fighters.map(f=>f.ready)))render(previous);else updateClock();}
 function targetIds(a,own){return data.fighters.filter(f=>f.hp>0&&(a.target==='self'?f.user_id===own.user_id:a.target==='ally'?f.team===own.team&&!(a.id==='protect'&&f.user_id===own.user_id):f.team!==own.team)).map(f=>f.user_id);}
 function render(previous){
 const own=data.fighters.find(f=>f.user_id===current.userId),combat=data.combat,b=data.battle,active=data.fighters.find(f=>f.user_id===combat.active_id);body.replaceChildren();
 const top=element('div','combat-topline');top.append(element('small','eyebrow',b.context?.rivalry_id?'RIVAL BATTLE':b.context?.party_battle?'FRIENDLY 2V2':'FRIENDLY DUEL'),btn('Return',()=>returnToOrigin()));body.append(top);
 if(b.type==='discussion')body.append(element('p','combat-discussion-context',`“${b.context?.statement||b.topic}”`),element('p','muted','A Kaidra-style contest. Combat does not prove the claim true.'));
 if(b.flavour_text)body.append(element('p','combat-flavour',b.flavour_text));
 if(b.context?.party_battle){const names=element('div','combat-party-names');names.append(element('strong','',b.context.party_a_name),element('span','','VS'),element('strong','',b.context.party_b_name));body.append(names);}
 const field=element('div','combat-field');field.classList.toggle('combat-team-field',data.fighters.length>2);const sides=own?[3-own.team,own.team]:[2,1];
 for(const team of sides){const side=element('div','combat-team');side.dataset.team=team;for(const f of data.fighters.filter(f=>f.team===team)){const meta=battleClasses[f.class_id||f.identity?.class_id],node=element('article','combat-fighter');node.dataset.fighterId=f.user_id;node.dataset.class=f.class_id||f.identity?.class_id||'undetermined';node.style.setProperty('--fighter-color',meta?.color||'#a7a0b1');node.classList.toggle('is-defeated',f.hp===0&&combat.phase!=='waiting');node.classList.toggle('is-turn',f.user_id===combat.active_id);
 const title=element('div','fighter-heading');title.append(element('strong','',f.name),element('small','',meta?.name||'Awaiting awakening'));if(f.identity?.league_label)title.append(element('small','',f.identity.league_label));node.append(title);
 const character=btn('',()=>{if(!selection||!own)return;const a=(data.abilities||[]).find(a=>a.id===selection.ability)||{id:'basic',target:'enemy'};if(targetIds(a,own).includes(f.user_id)){selection.target=f.user_id;render(data);}},'combat-character');character.setAttribute('aria-label',`Select ${f.name}`);character.append(classEmblem(f.class_id||f.identity?.class_id));if(f.avatar_url)character.append(artwork(f.avatar_url,'','fighter-avatar'));node.append(character);
 if(selection&&own){const a=(data.abilities||[]).find(a=>a.id===selection.ability)||{id:'basic',target:'enemy'},eligible=targetIds(a,own).includes(f.user_id);character.disabled=!eligible||busy;node.classList.toggle('is-eligible',eligible);node.classList.toggle('is-selected',selection.target===f.user_id);if(eligible)node.append(element('small','fighter-target-label',selection.target===f.user_id?'TARGET SELECTED':'TAP TO TARGET'));}
 if(combat.phase!=='waiting'){const hp=element('div','fighter-hp'),bar=element('span','fighter-hp-fill');const old=previous?.fighters.find(p=>p.user_id===f.user_id);bar.style.width=`${(old?.hp??f.hp)/f.max_hp*100}%`;hp.append(bar);hp.setAttribute('role','progressbar');hp.setAttribute('aria-label',`${f.name} HP`);hp.setAttribute('aria-valuenow',String(f.hp));hp.setAttribute('aria-valuemin','0');hp.setAttribute('aria-valuemax',String(f.max_hp));node.append(hp,element('small','fighter-hp-label',`HP ${f.hp} / ${f.max_hp}`));requestAnimationFrame(()=>bar.style.width=`${f.hp/f.max_hp*100}%`);
 const resource=element('div','fighter-resource'),fill=element('span');fill.style.width=`${f.resource}%`;resource.append(fill);node.append(resource,element('small','fighter-resource-label',`${({warrior:'Stamina',wizard:'Mana',ninja:'Energy',guardian:'Guard',rogue:'Momentum',healer:'Spirit',ranger:'Focus',berserker:'Rage'})[f.class_id]} ${f.resource} / 100`));const statuses=element('div','fighter-statuses');for(const e of data.effects.filter(e=>e.target===f.user_id)){const status=element('span','fighter-status',`${e.kind.replaceAll('_',' ')}${e.amount?' '+e.amount:''}`);status.title=`${e.kind.replaceAll('_',' ')} · ${Math.max(0,e.expires-f.turns)} own turns remaining`;status.tabIndex=0;statuses.append(status);}node.append(statuses);
 }else node.append(element('small','muted',f.ready?'READY':'AWAITING ACCEPTANCE'));
 side.append(node);}field.append(side);}body.append(field);
 if(combat.phase==='waiting'&&b.status==='pending'){
 body.append(element('p','combat-waiting','Every invited fighter must accept before combat begins. Invitations expire after 10 minutes. Predictions close when the battle starts.'));
 if(own&&!own.ready)body.append(btn(data.fighters.length>2?'Accept 2v2':'Accept duel',async()=>{try{if(!await awakenBattleIdentity())return;await chatAction('kaidra_battle_action',{target_battle:id,action:'accept'});await load();}catch(error){notify(error.message||'Could not accept.');}},'primary-button'),btn('Decline',async()=>{try{await chatAction('kaidra_battle_action',{target_battle:id,action:'decline'});load();}catch(error){notify(error.message||'Could not decline.');}}));
 if(b.challenger_id===current.userId)body.append(btn('Cancel challenge',async()=>{try{await chatAction('kaidra_battle_action',{target_battle:id,action:'cancel'});load();}catch(error){notify(error.message||'Could not cancel.');}}));
 if(!own){headingPrediction();}
 }else if(combat.phase==='playing'){
 const turn=element('div','combat-turn');turn.append(element('strong','',combat.active_id===current.userId?'YOUR TURN':`${active?.name||'Fighter'} IS CHOOSING`),element('span','combat-clock',''),element('small','',`Round ${combat.round}${combat.round>12?' · Pressure rising':''}`));body.append(turn);
 if(own&&own.hp>0&&combat.active_id===own.user_id)renderActions(own);else body.append(element('p','combat-waiting',own?.hp===0?'You are defeated. Your teammate may continue.':'Watch the arena. Your fighter acts only on your own turn.'));
 if(own&&own.hp>0)body.append(btn(data.fighters.length>2?'Concede my fighter':'Surrender',async()=>{if(await confirmAction('Concede your fighter?',data.fighters.length>2?'Your teammate continues fighting.':'Your opponent wins this duel.','Concede'))submit('surrender');},'combat-surrender'));
 }else {
 const won=own&&own.team===combat.winning_team,hasResult=b.status==='resolved',result=element('section','combat-result');result.dataset.result=won?'victory':'defeat';result.append(element('small','eyebrow',hasResult?'BATTLE COMPLETE':b.status.toUpperCase()),element('h2','',hasResult?(combat.winning_team==null?'DRAW':own?won?'VICTORY':'DEFEAT':'BATTLE FINISHED'):'CHALLENGE CLOSED'));if(hasResult){const winners=data.fighters.filter(f=>f.team===combat.winning_team);result.append(element('p','',winners.map(f=>f.name).join(' + ')),element('p','muted','Friendly battles do not change League rating.'));if(own){const xp=data.own_rewards?.[0]?.xp??0;result.append(element('p','combat-xp',`+${xp} XP`));if(!xp)result.append(element('small','muted','This match did not grant progression rewards.'));result.append(progressionCard(data.own_stats||{}));const rematch=btn('Rematch',()=>document.dispatchEvent(new CustomEvent('kaidra:combat-rematch',{detail:{battle:b,fighters:data.fighters}})),'primary-button');result.append(rematch);}}result.append(btn('Return to conversation',returnToOrigin));body.append(result);if(hasResult)headingPrediction();
 }
 if(data.events.length){const log=element('details','combat-log');log.append(element('summary','','Battle history'));for(const entry of data.events){const row=element('div','combat-log-turn');for(const event of entry.payload.events){const text=summary(event,data);if(text)row.append(element('p','',text));}if(row.children.length)log.append(row);}body.append(log);}
 body.append(errorNode);updateClock();
 if(previous&&data.combat.revision>previous.combat.revision)animate(data.events.at(-1)?.payload.events||[]);
 }
 function headingPrediction(){const total=data.predictions.reduce((n,p)=>n+p.count,0),box=element('div','combat-predictions');box.append(element('small','eyebrow',data.combat.phase==='waiting'?'WHO WILL WIN?':'SPECTATOR PREDICTIONS'));for(const f of data.fighters){const count=data.predictions.find(p=>p.side===f.user_id)?.count||0;const text=`${f.name}${total?' · '+Math.round(count/total*100)+'%':''}`;if(data.combat.phase==='waiting')box.append(btn(text,async()=>{try{await chatAction('kaidra_battle_action',{target_battle:id,action:'predict',value:f.user_id});load();}catch(error){notify(error.message||'Could not predict.');}}));else box.append(element('span','',text));}box.append(element('p','muted','Predictions never affect combat or XP.'));body.append(box);}
 function renderActions(own){const tray=element('section','combat-actions');tray.setAttribute('aria-label','Your combat abilities');const abilities=[...(data.abilities||[]),{id:'basic',name:'Basic Attack',target:'enemy',cost:0,cooldown:0,min:10,max:14,description:'A low-pressure fallback when resources run short.'}];
 if(selection){const a=abilities.find(a=>a.id===selection.ability);tray.append(element('strong','',a.target==='all_enemies'?'ALL LIVING ENEMIES':selection.target?'CONFIRM YOUR ACTION':'SELECT A TARGET'),element('p','',a.name),element('p','muted',a.description));const chosen=data.fighters.find(f=>f.user_id===selection.target);const confirm=btn(`Use ${a.name}${chosen?' → '+chosen.name:''}`,()=>submit('act',a.id,a.target==='all_enemies'?null:selection.target),'primary-button');confirm.disabled=busy||a.target!=='all_enemies'&&!selection.target;tray.append(confirm,btn('Choose another ability',()=>{selection=null;render(data);}));}
 else {const grid=element('div','combat-ability-grid');for(const a of abilities){const ready=data.cooldowns.find(c=>c.user_id===own.user_id&&c.ability_id===a.id)?.ready_turn||0,cooldown=Math.max(0,ready-own.turns),resource=own.resource<a.cost,condition=a.condition==='low_hp'&&own.hp/own.max_hp>.35,targets=targetIds(a,own),disabled=busy||cooldown>0||resource||condition||!targets.length,card=element('article','combat-ability'),action=btn('',()=>{selection={ability:a.id,target:a.target==='self'?own.user_id:a.target==='enemy'&&targets.length===1?targets[0]:null};render(data);},'combat-ability-button');action.disabled=disabled;action.append(element('strong','',a.name),element('small','',a.min!=null?`${a.min}–${a.max} damage${a.hits?' × '+a.hits:''}`:a.amount!=null?`${a.amount} ${a.kind==='heal'?'healing':a.kind==='shield'?'shield':'effect'}`:'Tactical action'),element('small','',cooldown?`Cooldown · ${cooldown} own turns`:resource?`${a.cost} resource required`:condition?'Requires HP at most 35%':`${a.cost} resource · ${a.cooldown} turn cooldown`));const info=element('details','combat-ability-info');info.append(element('summary','','Ability details'),element('p','',a.description),element('small','',`Target: ${a.target.replaceAll('_',' ')}${a.duration?' · Duration: '+a.duration+' own turns':''}`));card.append(action,info);grid.append(card);}tray.append(grid);}body.append(tray);}
 async function submit(action,ability=null,target=null){if(busy||!data)return;busy=true;errorNode.textContent='';const previous=data;pendingIntent ||= {action,battle_id:id,ability_id:ability,target_id:target,request_id:crypto.randomUUID(),expected_revision:data.combat.revision};render(data);try{const next=await request(pendingIntent);pendingIntent=null;busy=false;selection=null;update(next);}catch(error){busy=false;errorNode.textContent=error.message;await load();if(data?.combat.revision===previous.combat.revision){pendingIntent=null;render(data);}else pendingIntent=null;}}
 function updateClock(){if(data?.combat.phase==='waiting'&&Date.now()+clockOffset>=Date.parse(data.battle.created_at)+600000&&triedTimeout!==revision){triedTimeout=revision;load();}const clock=body.querySelector('.combat-clock');if(clock&&data?.combat.deadline){const seconds=Math.max(0,Math.ceil((Date.parse(data.combat.deadline)-(Date.now()+clockOffset))/1000));clock.textContent=`00:${String(seconds).padStart(2,'0')}`;clock.classList.toggle('is-urgent',seconds<=5);if(!seconds&&triedTimeout!==revision&&!busy){triedTimeout=revision;load();}}}
 function returnToOrigin(){if(data?.battle.discussion_message_id)document.dispatchEvent(new CustomEvent('kaidra:jump-discussion',{detail:{conversationId:data.battle.conversation_id,messageId:data.battle.discussion_message_id}}));else goRoute(`inbox/${data?.battle.conversation_id||''}`);}
 function animate(events){for(const e of events){const source=body.querySelector(`[data-fighter-id="${e.source}"]`),target=body.querySelector(`[data-fighter-id="${e.target}"]`);if(e.kind==='ability_used'){source?.classList.add('is-attacking');setTimeout(()=>source?.classList.remove('is-attacking'),1100);}if(['damage','heal','pressure','recoil'].includes(e.kind)&&target){const float=element('span',`combat-number ${e.kind}`,`${e.kind==='heal'?'+':'−'}${e.amount}`);target.append(float);target.classList.add(e.kind==='heal'?'is-healing':'is-hit');setTimeout(()=>{float.remove();target.classList.remove('is-healing','is-hit');},1000);}if(e.kind==='status_applied'&&['shield','guard','guard_once','counter'].includes(e.status))target?.classList.add('is-blocking');}}
 const finish=event=>{if(event.detail.id!==panel.id)return;clearInterval(timer);clearInterval(poll);if(visibility)document.removeEventListener('visibilitychange',visibility);if(channel)supabase.removeChannel(channel);document.removeEventListener('kaidra:modal-close',finish);if(arena===state)arena=null;if(parseRoute(location.hash).view==='battle'&&parseRoute(location.hash).id===id)backRoute('inbox');};document.addEventListener('kaidra:modal-close',finish);
 await load();if(!panel.modal.isConnected)return;
 channel=supabase.channel(`combat:${id}`).on('postgres_changes',{event:'*',schema:'public',table:'battle_events',filter:`battle_id=eq.${id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'battle_participants',filter:`battle_id=eq.${id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'battles',filter:`id=eq.${id}`},load).subscribe(status=>{connected=status==='SUBSCRIBED';if(connected)load();});
 timer=setInterval(updateClock,1000);let lastSync=Date.now();poll=setInterval(()=>{if(document.visibilityState==='visible'&&Date.now()-lastSync>(connected?60000:15000)){lastSync=Date.now();load();}},5000);
 visibility=()=>{if(document.visibilityState==='visible'&&arena===state)load();};document.addEventListener('visibilitychange',visibility);
}
document.addEventListener('kaidra:route-change',event=>{if(arena&&(event.detail.view!=='battle'||event.detail.id!==arena.id))arena.close();});
