import {chatAction} from './supabase-client.js';
import {element,actionButton,avatar,notify} from './ui.js';
import {dialog,confirmAction} from './context-menu.js';
import {account} from './session.js';
import {parseRoute,goRoute,backRoute} from './router.js';
const links=new Map();
export async function groupInvitePanel(state) {
  const panel=dialog('Invite to group','group-invite-panel'),copy=element('div','group-invite-content'),error=element('p','form-error');panel.card.append(copy,error);panel.open();let busy=false;
  async function render(){copy.replaceChildren(element('p','muted','Loading invite settings…'));try{const status=await chatAction('kaidra_group_link_manage',{target_conversation:state.id,operation:'status'});if(!panel.modal.isConnected)return;copy.replaceChildren();const saved=links.get(state.id);const url=saved?.expires>Date.now()&&status.active?saved.url:null;
    copy.append(avatar(state.profile,'group-info-avatar'),element('h3','',state.profile.display_name),element('p','muted',status.approval?'An admin must approve people who request to join.':'People with this link can join. Share it with people you trust.'));
    if(url){const input=element('input');input.value=url;input.readOnly=true;input.setAttribute('aria-label','Group invitation link');input.addEventListener('focus',()=>input.select());copy.append(input);const share=actionButton('Share invite','share','primary-button'),clip=actionButton('Copy link','copy');share.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:state.profile.display_name,url});else{await navigator.clipboard.writeText(url);notify('Invite link copied');}}catch(problem){if(problem.name!=='AbortError')error.textContent='Could not share. Select the link to copy it.';}});clip.addEventListener('click',()=>navigator.clipboard.writeText(url).then(()=>notify('Invite link copied')).catch(()=>error.textContent='Select the link to copy it.'));copy.append(share,clip);}
    if(status.active)copy.append(element('small','muted',`Expires ${new Date(status.expires_at).toLocaleString()}`));
    const create=actionButton(status.active?'Create replacement link':'Create invite link','link'),revoke=actionButton('Revoke link','close','danger-button');create.addEventListener('click',async()=>{if(busy)return;if(status.active&&!await confirmAction('Replace invitation link?','The previous link will stop working.','Replace link'))return;busy=true;create.disabled=true;try{const data=await chatAction('kaidra_group_link_manage',{target_conversation:state.id,operation:'create'});const invite=new URL('/app.html',location.origin);invite.hash='join/'+data.token;links.set(state.id,{url:invite.href,expires:new Date(data.expires_at).getTime()});await render();}catch(problem){error.textContent=problem.message||'Could not create invite.';}finally{busy=false;create.disabled=false;}});
    revoke.addEventListener('click',async()=>{if(busy||!await confirmAction('Revoke invitation link?','Anyone using it will no longer be able to join.','Revoke'))return;busy=true;try{await chatAction('kaidra_group_link_manage',{target_conversation:state.id,operation:'revoke'});links.delete(state.id);await render();}catch(problem){error.textContent=problem.message;}finally{busy=false;}});copy.append(create);if(status.active)copy.append(revoke);
    copy.append(element('p','muted','Links expire after seven days. Creating a replacement immediately revokes the previous link. Existing members keep their access.'));
  }catch(problem){copy.replaceChildren();error.textContent=problem.message||'Invite links are unavailable.';}}await render();
}
export async function groupRequestPanel(state,onChange) {
  const panel=dialog('Join requests','group-requests-panel'),list=element('div','people-list'),error=element('p','form-error');panel.card.append(list,error);panel.open();
  async function load(){list.replaceChildren(element('p','muted','Loading requests…'));try{const people=await chatAction('kaidra_group_requests',{target_conversation:state.id});if(!panel.modal.isConnected)return;list.replaceChildren();if(!people.length)list.append(element('p','muted','No pending requests.'));for(const person of people){const row=element('div','person-row'),name=element('span','person-copy');name.append(element('strong','',person.display_name||person.username),element('small','muted','@'+person.username));row.append(avatar(person),name);for(const decision of ['approve','reject']){const button=actionButton(decision==='approve'?'Approve':'Decline',decision==='approve'?'check':'close');button.addEventListener('click',async()=>{row.querySelectorAll('button').forEach(b=>b.disabled=true);try{await chatAction('kaidra_group_requests',{target_conversation:state.id,target_user:person.id,decision});await onChange();await load();}catch(problem){error.textContent=problem.message;row.querySelectorAll('button').forEach(b=>b.disabled=false);}});row.append(button);}list.append(row);}}catch(problem){error.textContent=problem.message;}}await load();
}
let routeTicket=0,joinPanel;
async function openJoin(route){const ticket=++routeTicket;if(route.view!=='join'){if(joinPanel){const previous=joinPanel;joinPanel=null;previous.close();}return;}if(joinPanel?.token===route.id)return;const current=await account;if(!current||ticket!==routeTicket)return;const panel=dialog('Group invitation','group-join-panel');panel.token=route.id;joinPanel=panel;const body=element('div','group-invite-content'),error=element('p','form-error');panel.card.append(body,error);panel.open();body.append(element('p','muted','Opening your invitation…'));
  try{const preview=await chatAction('kaidra_group_join',{invite_token:route.id});if(ticket!==routeTicket||!panel.modal.isConnected)return;body.replaceChildren();body.append(avatar({display_name:preview.title,avatar_url:preview.avatar_url},'group-info-avatar'),element('h3','',preview.title),element('p','muted',`${preview.count} members`));if(preview.description)body.append(element('p','',preview.description));
    if(preview.status==='member'){const open=actionButton('Open group','chat','primary-button');open.addEventListener('click',()=>{sessionStorage.removeItem('kaidra:join-destination');goRoute('inbox/'+preview.id);});body.append(open);}else if(preview.status==='pending')body.append(element('p','muted','Your request is pending. An admin will review it.'));else{const join=actionButton(preview.approval?'Request to join':'Join group','people','primary-button');join.addEventListener('click',async()=>{join.disabled=true;error.textContent='';try{const result=await chatAction('kaidra_group_join',{invite_token:route.id,join_now:true});if(result.status==='pending'){body.replaceChildren(element('h3','','Request sent'),element('p','muted','An admin will review your request.'));}else{sessionStorage.removeItem('kaidra:join-destination');document.dispatchEvent(new CustomEvent('kaidra:social-refresh'));goRoute('inbox/'+result.id);}}catch(problem){error.textContent=problem.message||'Could not join this group.';join.disabled=false;}});body.append(element('p','muted',preview.approval?'An admin approves new members.':'Joining gives you access to this group and its shared history.'),join);}
  }catch(problem){body.replaceChildren();error.textContent=problem.message||'This invitation is unavailable or expired.';}
}
document.addEventListener('kaidra:route-change',event=>openJoin(event.detail));
document.addEventListener('kaidra:modal-close',event=>{if(event.detail.id===joinPanel?.id&&parseRoute(location.hash).view==='join')backRoute('inbox');});
account.then(()=>openJoin(parseRoute(location.hash)));
