import { account } from './session.js';
import { supabase } from './supabase-client.js';
import { element, artwork, actionButton, emptyState, notify, openModal, closeModal } from './ui.js';
import { confirmAction, dialog } from './context-menu.js';
import { goRoute, parseRoute } from './router.js';
import { contentRequest, renderNews } from './content-client.js';
import { sportsRequest, sportsRpc, sportsRef, sportsPath, sportsFollows, sportsRegistry } from './sports-client.js';
let generation=0, detailGeneration=0;
const button=(text,fn,cls='quiet-button')=>{const b=actionButton(text,null,cls);b.addEventListener('click',fn);return b;};
const heading=(target,text)=>target.append(element('h3','sports-section-title',text));
const rows=data=>data?.response||[];
const datetime=value=>value?new Date(value).toLocaleString([], {weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Kickoff to be confirmed';
function stamp(target,data){const text=data.offline?'Offline · saved snapshot':data.stale?'Saved snapshot · updates unavailable':`Updated ${datetime(data.fetched_at)}`;target.append(element('p','sports-freshness',text));if(data.limited_scope==='today')target.append(element('p','sports-unavailable','The provider plan limits upcoming/recent fixture queries. Showing covered matches today only.'));}
function failure(target,error,retry){target.replaceChildren(element('p','sports-unavailable',error.message||'This section is unavailable.'));if(retry)target.append(button('Try again',retry));}
function teamCard(row){const t=row.team||row.league||row.player||row,type=row.league?'competition':row.player?'player':'team',b=button('',()=>goRoute(sportsPath(sportsRef(type,t.id))),'sports-entity-card');if(t.logo||t.photo)b.append(artwork(t.logo||t.photo,'','sports-logo'));b.append(element('strong','',t.name||'Participant'));if(t.country||t.position)b.append(element('small','muted',t.country||t.position));return b;}
function fixtureCard(row,data){const b=button('',()=>goRoute(sportsPath(sportsRef('event',row.fixture.id))),'sports-fixture');const recent=!data?.stale&&Date.now()-Date.parse(data?.fetched_at)<360000,st=row.fixture.status;const active=['1H','HT','2H','ET','BT','P'].includes(st.short);b.append(element('small','sports-match-meta',`${row.league.name} · ${active&&!recent?'Last reported: ':''}${st.long}${st.elapsed!=null?' · '+st.elapsed+'′':''}`));for(const side of ['home','away']){const t=row.teams[side],line=element('span','sports-score-line');if(t.logo)line.append(artwork(t.logo,'','sports-logo'));line.append(element('strong','',t.name),element('b','',row.goals?.[side]==null?'—':String(row.goals[side])));b.append(line);}b.append(element('time','muted',datetime(row.fixture.date)));return b;}
function fixtureList(target,data){stamp(target,data);const matches=rows(data);if(!matches.length){target.append(emptyState('No fixtures returned','This date or competition may have no covered matches. Try another section.','ball'));return;}const list=element('div','sports-fixtures');list.append(...matches.slice(0,20).map(row=>fixtureCard(row,data)));target.append(list);if(matches.length>20)target.append(element('p','muted',`Showing 20 of ${matches.length} matches. Open a club or competition to narrow the view.`));}
function tabs(target,items){const nav=element('div','sports-tabs'),body=element('section','sports-tab-body');target.append(nav,body);let revision=0;
 const activate=async(index)=>{const n=++revision;[...nav.children].forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',String(i===index));});body.replaceChildren(element('p','muted','Loading…'));try{await items[index][1](body);}catch(error){if(n===revision)failure(body,error,()=>activate(index));}};
 for(const [i,[label]] of items.entries())nav.append(button(label,()=>activate(i)));
 // Render into detached containers, so slow previous tabs cannot overwrite a new tab.
 const original=items.map(([,fn])=>fn);items.forEach((entry,i)=>entry[1]=async target=>{const fragment=element('div','sports-panel');await original[i](fragment);if(nav.children[i].getAttribute('aria-pressed')==='true')target.replaceChildren(fragment);});activate(0);
}
function searchPanel(target,kind='team'){const form=element('form','sports-search'),label=element('label','sr-only',kind==='player'?'Search football players':'Search football clubs'),input=element('input'),submit=actionButton('Search','search','primary-button'),results=element('div','sports-directory');input.id=`sports-search-${kind}`;label.htmlFor=input.id;input.type='search';input.placeholder=kind==='player'?'Find a player · minimum 3 characters':'Search Arsenal, Chelsea, Barcelona…';input.maxLength=60;submit.type='submit';form.append(label,input,submit);target.append(form,results);let timer,version=0;
 async function run(){const n=++version,q=input.value.trim();if(q.length<3){results.replaceChildren(element('p','muted','Type at least three characters.'));return;}results.replaceChildren(element('p','muted','Searching…'));try{const data=await sportsRequest(kind==='player'?'player-search':'search',{query:q});if(n!==version||!target.isConnected)return;results.replaceChildren(...rows(data).map(teamCard));if(!rows(data).length)results.append(element('p','muted','No matches. Try the club or player’s official name.'));stamp(results,data);}catch(error){if(n===version)failure(results,error);}}
 input.addEventListener('input',()=>{clearTimeout(timer);++version;timer=setTimeout(run,500);});form.addEventListener('submit',e=>{e.preventDefault();clearTimeout(timer);run();});results.append(element('p','muted','Search the full provider directory, beyond today’s fixtures.'));
 if(kind==='team'){const samples=element('div','sports-tabs');for(const q of ['Arsenal','Chelsea','Barcelona','Real Madrid'])samples.append(button(q,()=>{input.value=q;clearTimeout(timer);run();}));target.append(samples);}
}
export async function renderSportsHub(route){const n=++generation,hero=document.getElementById('discover-hero'),grid=document.getElementById('discover-grid'),nav=document.getElementById('discover-sections');hero.className='discover-hero sports-hero';hero.replaceChildren(element('span','eyebrow','KAIDRA / SPORTS'),element('h2','','Follow the game. Find your people.'),element('p','','Your clubs, real matches and the conversations they start.'));grid.classList.add('sports-grid');grid.replaceChildren();nav.replaceChildren();document.getElementById('discover-heading').textContent='Football';document.getElementById('discover-context').textContent='API-Sports · scores are snapshots, with update times';document.getElementById('discover-more').classList.add('hidden');document.getElementById('discover-filters').replaceChildren();
 const sports=element('div','sports-tabs');for(const [id,s] of Object.entries(sportsRegistry)){const b=button(s.name,()=>id!=='football'&&notify(`${s.name} coverage is planned.`));b.classList.toggle('active',id==='football');if(!s.enabled)b.append(element('small','',' · Planned'));sports.append(b);}hero.append(sports);
 const sections=[['for-you','For you'],['today','Today'],['clubs','Clubs'],['competitions','Competitions'],['players','Players'],['news','News']];const section=route.section==='popular'?'for-you':route.section;
 for(const [id,name] of sections){const b=button(name,()=>goRoute(`discover/sports/${id}`));b.classList.toggle('active',id===section);b.setAttribute('aria-pressed',String(id===section));nav.append(b);}
 const target=element('div','sports-world');grid.append(target);
 try{
 if(section==='clubs'){searchPanel(target);return;}
 if(section==='players'){searchPanel(target,'player');return;}
 if(section==='news'){renderNews(target,(await contentRequest('news',{kind:'football'})).items||[]);return;}
 if(section==='competitions'){const data=await sportsRequest('competitions');if(n!==generation)return;const list=element('div','sports-directory');list.append(...rows(data).slice(0,60).map(teamCard));target.append(list);stamp(target,data);if(rows(data).length>60){const more=button('More competitions',()=>{const offset=list.children.length;list.append(...rows(data).slice(offset,offset+60).map(teamCard));more.hidden=list.children.length>=rows(data).length;});target.append(more);}return;}
 if(section==='today'){const data=await sportsRequest('fixtures',{mode:'today'});if(n===generation)fixtureList(target,data);return;}
 const follows=await sportsFollows();if(n!==generation)return;const primary=follows.find(f=>f.is_primary);
 if(primary){const e=primary.sports_entities;heading(target,'Your club');const identity=element('div','sports-supported');identity.append(teamCard(e.snapshot),button('Notification preferences',openSportsPreferences));target.append(identity);tabs(target,[['Next matches',async box=>fixtureList(box,await sportsRequest('fixtures',{team:primary.external_id,mode:'upcoming'}))],['Results',async box=>fixtureList(box,await sportsRequest('fixtures',{team:primary.external_id,mode:'results'}))],['Squad',async box=>renderSquad(box,primary.external_id)],['Standings',async box=>renderTeamStandings(box,primary.external_id)]]);}
 else {target.append(element('h3','','Which club has your heart?'),element('p','muted','Support one primary club, follow others, and keep your choices private unless you choose to share them.'));searchPanel(target);target.append(button('Browse today’s matches',()=>goRoute('discover/sports/today')));}
 if(follows.some(f=>!f.is_primary)){heading(target,'Following');const directory=element('div','sports-directory');directory.append(...follows.filter(f=>!f.is_primary).map(f=>teamCard(f.sports_entities.snapshot)));target.append(directory);}
 }catch(error){if(n===generation)failure(target,error,()=>renderSportsHub(route));}
}
async function renderSquad(target,id){const data=await sportsRequest('squad',{id});stamp(target,data);const players=rows(data)[0]?.players||[];if(!players.length){target.append(element('p','muted','The provider has not returned a registered squad.'));return;}for(const position of [...new Set(players.map(p=>p.position||'Other'))]){heading(target,position);const list=element('div','sports-directory');for(const p of players.filter(p=>(p.position||'Other')===position)){const b=teamCard({player:p});b.append(element('small','muted',[p.number!=null?'#'+p.number:'',p.age?p.age+' years':''].filter(Boolean).join(' · ')));list.append(b);}target.append(list);}}
async function renderTeamStandings(target,id){const data=await sportsRequest('competitions',{id}),competitions=rows(data).filter(r=>{const s=currentSeason(r);return s?.current&&s.coverage?.standings;});if(!competitions.length){target.append(element('p','muted','No current competition with standings coverage was returned.'));return;}const label=element('label','sports-season','Competition'),select=element('select'),body=element('div');for(const r of competitions){const o=element('option','',r.league.name);o.value=r.league.id;select.append(o);}label.append(select);target.append(label,body);let version=0;const load=async()=>{const n=++version,r=competitions.find(r=>String(r.league.id)===select.value),fragment=element('div');body.replaceChildren(element('p','muted','Loading standings…'));try{await renderStandings(fragment,r.league.id,currentSeason(r).year);if(n===version)body.replaceChildren(fragment);}catch(error){if(n===version)failure(body,error,load);}};select.addEventListener('change',load);await load();}
function currentSeason(row){return row.seasons?.find(s=>s.current)||[...(row.seasons||[])].sort((a,b)=>b.year-a.year)[0];}
async function renderStandings(target,id,season){const data=await sportsRequest('standings',{id,season});stamp(target,data);const groups=rows(data)[0]?.league?.standings||[];if(!groups.length){target.append(element('p','muted','Standings are unavailable for this competition and season.'));return;}for(const group of groups){const wrap=element('div','sports-table-wrap'),table=element('table','sports-table'),caption=element('caption','',`${rows(data)[0].league.name} · ${season}`),thead=element('thead'),header=element('tr');for(const label of ['#','Team','P','GD','Pts'])header.append(element('th','',label));thead.append(header);table.append(caption,thead);const tbody=element('tbody');for(const r of group){const tr=element('tr');tr.append(element('td','',String(r.rank)));const td=element('td');td.append(button(r.team.name,()=>goRoute(sportsPath(sportsRef('team',r.team.id)))));tr.append(td,element('td','',String(r.all.played)),element('td','',String(r.goalsDiff)),element('td','',String(r.points)));tbody.append(tr);}table.append(tbody);wrap.append(table);target.append(wrap);}}
async function renderTeamCompetitions(target,id){const data=await sportsRequest('competitions',{id});stamp(target,data);const competitions=rows(data).filter(r=>r.seasons?.some(s=>s.current));if(!competitions.length){target.append(element('p','muted','No current competitions were returned.'));return;}for(const r of competitions)target.append(teamCard(r));target.append(element('p','muted','Open a competition for standings, fixtures and clubs.'));}
function reference(type,id,name,image){return {...sportsRef(type,id),kind:'sports',title:name,image};}
function actions(target,ref){const row=element('div','detail-actions');row.append(button('Share',()=>{closeModal('content-detail-modal');document.dispatchEvent(new CustomEvent('kaidra:share-content',{detail:{content:ref,text:''}}));}),button('Start a Discussion',()=>{const panel=dialog('Sports Discussion','sports-discussion-dialog'),form=element('form'),input=element('textarea'),send=actionButton('Choose a conversation','chat','primary-button');input.placeholder='Make a statement people can agree or disagree with…';input.maxLength=4000;input.required=true;input.setAttribute('aria-label','Discussion statement');send.type='submit';form.append(element('p','muted',ref.title),input,send);panel.card.append(form);form.addEventListener('submit',e=>{e.preventDefault();if(!input.value.trim())return;panel.close();closeModal('content-detail-modal');document.dispatchEvent(new CustomEvent('kaidra:share-content',{detail:{text:input.value.trim(),discussionContext:ref}}));});panel.open();}));target.append(row);}
async function followActions(target,ref){let follows=await sportsFollows(),own=follows.find(f=>f.entity_type===ref.entity_type&&f.external_id===ref.external_id),primary=follows.find(f=>f.is_primary);const container=element('div','sports-follow-panel');target.append(container);target=container;const row=element('div','sports-follow-actions');target.append(row);
 const act=async action=>{let expected=null;if(action==='support'&&primary&&primary.external_id!==ref.external_id){if(!await confirmAction('Change supported club?',`Change from ${primary.sports_entities.display_name} to ${ref.title}?`,'Change club'))return;expected=primary.external_id;}
 try{await sportsRpc('kaidra_sports_follow',{entity:ref,action,public_choice:own?.is_public||false,expected_primary:expected});document.dispatchEvent(new Event('kaidra:sports-updated'));const parent=container.parentElement;container.remove();await followActions(parent,ref);}catch(error){notify(error.message||'Could not save your sports preference.');}};
 if(ref.entity_type==='team')row.append(button(own?.is_primary?'Supporting · remove support':'Support '+ref.title,()=>act(own?.is_primary?'unfollow':'support'),own?.is_primary?'quiet-button':'primary-button'));
 if(!own?.is_primary)row.append(button(own?'Unfollow':'Follow',()=>act(own?'unfollow':'follow')));
 if(own){const label=element('label','checkbox-row'),privacy=element('input');privacy.type='checkbox';privacy.checked=own.is_public;label.append(privacy,document.createTextNode('Show on my public profile'));privacy.addEventListener('change',async()=>{privacy.disabled=true;try{await sportsRpc('kaidra_sports_follow',{entity:ref,action:'privacy',public_choice:privacy.checked});document.dispatchEvent(new Event('kaidra:sports-updated'));}catch{privacy.checked=!privacy.checked;notify('Privacy could not save.');}finally{privacy.disabled=false;}});row.append(label);}target.append(element('p','muted','Support is your primary club. Follow keeps other teams and competitions close. Private by default.'));
 if(ref.entity_type==='team'){const friends=await sportsRpc('kaidra_sports_friends',{entity:ref});if(friends.length){const context=element('div','sports-friend-context');context.append(element('strong','','Friends who support '+ref.title));for(const friend of friends)context.append(button(friend.display_name||friend.username,()=>goRoute('user/'+friend.id)));target.append(context);}}
}
async function matchSupport(target,row,ref){let state=await sportsRpc('kaidra_sports_match_social',{entity:ref});const wrap=element('div','sports-match-support');heading(wrap,'Your side for this match');const locked=!['NS','TBD','1H','HT','2H','ET','BT','P'].includes(row.fixture.status.short),publicLabel=element('label','checkbox-row'),privacy=element('input');privacy.type='checkbox';privacy.checked=state.own?.is_public||false;privacy.disabled=locked;publicLabel.append(privacy,document.createTextNode('Show my choice to friends'));wrap.append(publicLabel);for(const side of ['home','away','neutral']){const b=button(side==='neutral'?'Neutral':row.teams[side].name,async()=>{b.disabled=true;try{await sportsRpc('kaidra_sports_side',{entity:ref,choice:side,public_choice:privacy.checked});wrap.remove();await matchSupport(target,row,ref);}catch(error){notify(error.message||'Could not save match support.');b.disabled=locked;}});b.setAttribute('aria-pressed',String(state.own?.side===side));b.disabled=locked;wrap.append(b);}if(locked)wrap.append(element('p','muted','Support is locked. Your choice stays in match history.'));for(const friend of state.friends)wrap.append(element('p','muted',`${friend.name} supports ${friend.side==='neutral'?'neither side':row.teams[friend.side].name}`));target.append(wrap);}
async function renderMatch(target,id){const data=await sportsRequest('match',{id}),row=rows(data)[0];if(!row)throw new Error('This match was not returned by the provider.');stamp(target,data);const ref=reference('event',id,`${row.teams.home.name} vs ${row.teams.away.name}`);target.append(fixtureCard(row,data));actions(target,ref);if(row.fixture.venue?.name)target.append(element('p','muted',`${row.fixture.venue.name}${row.fixture.venue.city?' · '+row.fixture.venue.city:''}`));tabs(target,[['Overview',async box=>{box.append(button(row.league.name,()=>goRoute(sportsPath(sportsRef('competition',row.league.id)))));for(const t of [row.teams.home,row.teams.away])box.append(teamCard(t));await matchSupport(box,row,ref);}],['Events',async box=>{const d=await sportsRequest('events',{id});stamp(box,d);if(!rows(d).length)box.append(element('p','muted','No official events are available yet.'));for(const e of rows(d))box.append(element('p','sports-event',`${e.time.elapsed??''}${e.time.extra?'+'+e.time.extra:''}′ · ${e.team.name} · ${e.player?.name||''} · ${e.detail||e.type}`));}],['Lineups',async box=>{const d=await sportsRequest('lineups',{id});stamp(box,d);if(!rows(d).length)box.append(element('p','muted','Official lineups have not been returned. No starting or substitute status is assumed.'));for(const l of rows(d)){heading(box,`${l.team.name} · ${l.formation||'Official lineup'}`);heading(box,'Starting XI');for(const e of l.startXI||[])box.append(button(`${e.player.number??''} ${e.player.name}`,()=>goRoute(sportsPath(sportsRef('player',e.player.id)))));heading(box,'Substitutes');for(const e of l.substitutes||[])box.append(button(`${e.player.number??''} ${e.player.name}`,()=>goRoute(sportsPath(sportsRef('player',e.player.id)))));}}],['Statistics',async box=>{const d=await sportsRequest('statistics',{id});stamp(box,d);if(!rows(d).length)box.append(element('p','muted','Match statistics are unavailable.'));for(const t of rows(d)){heading(box,t.team.name);for(const s of t.statistics||[])if(s.value!==null)box.append(element('p','sports-stat',`${s.type}: ${s.value}`));}}]]);}
async function renderTeam(target,id){const data=await sportsRequest('team',{id}),row=rows(data)[0];if(!row)throw new Error('This club is not available.');const hero=element('div','sports-identity-hero');if(row.venue?.image)hero.append(artwork(row.venue.image,'','sports-venue'));hero.append(teamCard(row),element('p','muted',[row.team.country,row.team.founded?'Founded '+row.team.founded:'',row.venue?.name].filter(Boolean).join(' · ')));target.append(hero);stamp(target,data);const ref=reference('team',id,row.team.name,row.team.logo);actions(target,ref);await followActions(target,ref);tabs(target,[['Next matches',async box=>fixtureList(box,await sportsRequest('fixtures',{team:id,mode:'upcoming'}))],['Results',async box=>fixtureList(box,await sportsRequest('fixtures',{team:id,mode:'results'}))],['Squad',async box=>renderSquad(box,id)],['Standings',async box=>renderTeamStandings(box,id)],['Competitions',async box=>renderTeamCompetitions(box,id)]]);}
async function renderCompetition(target,id){const data=await sportsRequest('competition',{id}),row=rows(data)[0];if(!row)throw new Error('This competition is not available.');target.append(teamCard(row));stamp(target,data);const ref=reference('competition',id,row.league.name,row.league.logo);actions(target,ref);await followActions(target,ref);const seasons=[...(row.seasons||[])].sort((a,b)=>b.year-a.year),selected=currentSeason(row);if(!selected){target.append(element('p','muted','No covered seasons were returned.'));return;}const label=element('label','sports-season','Season'),select=element('select');for(const s of seasons){const option=element('option','',`${s.year}${s.current?' · Current':''}`);option.value=s.year;select.append(option);}select.value=selected.year;label.append(select);target.append(label);const sections=element('div');target.append(sections);const load=()=>{sections.replaceChildren();const season=Number(select.value);tabs(sections,[['Standings',async box=>renderStandings(box,id,season)],['Upcoming',async box=>fixtureList(box,await sportsRequest('fixtures',{league:id,season,mode:'upcoming'}))],['Results',async box=>fixtureList(box,await sportsRequest('fixtures',{league:id,season,mode:'results'}))],['Clubs',async box=>{const d=await sportsRequest('teams',{id,season});stamp(box,d);box.append(...rows(d).map(teamCard));if(!rows(d).length)box.append(element('p','muted','No clubs were returned for this season.'));}]]);};select.addEventListener('change',load);load();}
async function renderPlayer(target,id){const known=await supabase.from('sports_entities').select('snapshot,verified_at').eq('sport','football').eq('provider','api-sports').eq('entity_type','player').eq('external_id',id).maybeSingle();let data;try{data=await sportsRequest('player',{id});}catch(error){if(!known.data)throw error;target.append(element('p','muted',error.message));}const row=rows(data)[0]||known.data?.snapshot,p=row?.player;if(!p)throw new Error('This player profile is unavailable.');target.append(teamCard({player:p}),element('h3','',p.firstname&&p.lastname?`${p.firstname} ${p.lastname}`:p.name));for(const [label,value] of [['Position',p.position||known.data?.snapshot?.player?.position],['Nationality',p.nationality],['Age',p.age],['Born',p.birth?.date],['Shirt number',p.number??known.data?.snapshot?.player?.number]])if(value!=null)target.append(element('p','sports-stat',`${label}: ${value}`));if(known.data?.snapshot?.team){heading(target,'Registered squad');target.append(teamCard(known.data.snapshot.team),element('p','muted','Squad information last checked '+datetime(known.data.snapshot.squad_verified_at||known.data.verified_at)));}if(data)stamp(target,data);actions(target,reference('player',id,p.name,p.photo));const label=element('label','sports-season','Season statistics'),select=element('select');const placeholder=element('option','','Choose a season');placeholder.value='';select.append(placeholder);for(let year=new Date().getFullYear();year>=new Date().getFullYear()-6;year--){const option=element('option','',String(year));option.value=year;select.append(option);}label.append(select);target.append(label);const stats=element('div');target.append(stats);select.addEventListener('change',async()=>{stats.replaceChildren();if(!select.value)return;try{const d=await sportsRequest('player-stats',{id,season:Number(select.value)});stamp(stats,d);if(!rows(d).length)stats.append(element('p','muted','No statistics returned for this season.'));for(const item of rows(d))for(const s of item.statistics||[]){heading(stats,`${s.team.name} · ${s.league.name}`);for(const [name,value] of [['Appearances',s.games.appearences],['Goals',s.goals.total],['Assists',s.goals.assists],['Yellow cards',s.cards.yellow],['Red cards',s.cards.red]])if(value!=null)stats.append(element('p','sports-stat',`${name}: ${value}`));}}catch(error){failure(stats,error);}});target.append(element('p','muted','A complete former-player archive is not available. Season teams are historical statistics, not a current squad claim.'));}
async function openSports(route){const n=++detailGeneration;openModal('content-detail-modal');document.getElementById('content-detail-kind').textContent='Sports';document.getElementById('content-detail-title').textContent=route.entityType==='event'?'Match Center':({team:'Club',player:'Player',competition:'Competition'})[route.entityType];const target=document.getElementById('content-detail-body');target.replaceChildren();const panel=element('div','sports-detail');target.append(panel);try{await ({team:renderTeam,event:renderMatch,competition:renderCompetition,player:renderPlayer}[route.entityType])(panel,route.id);}catch(error){if(n===detailGeneration)failure(panel,error,()=>openSports(route));}}
export async function openSportsPreferences(){const panel=dialog('Sports notifications','sports-preferences-dialog'),form=element('form');panel.card.append(form);try{const {data,error}=await supabase.from('sports_notification_preferences').select('*').eq('sport','football').maybeSingle();if(error)throw error;const checks={};for(const [key,label] of [['enabled','Enable supported-club notifications'],['reminders','Match reminders · within one hour'],['results','Full-time results'],['lineups','Official lineups']]){const wrap=element('label','checkbox-row'),input=element('input');input.type='checkbox';input.checked=data?.[key]||false;checks[key]=input;wrap.append(input,document.createTextNode(label));form.append(wrap);}form.append(element('p','muted','All categories start off. Updates use shared server requests and depend on provider coverage. Your global Football notification switch also applies.'));const errorText=element('p','form-error'),save=actionButton('Save preferences','check','primary-button');save.type='submit';form.append(errorText,save);form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{await sportsRpc('kaidra_sports_preferences',Object.fromEntries(Object.entries(checks).map(([k,input])=>[k,input.checked])));panel.close();notify('Sports notifications saved.');}catch{errorText.textContent='Preferences could not save. Try again.';}finally{save.disabled=false;}});}catch{form.append(element('p','muted','Preferences could not load. Please try again.'));}panel.open();}
document.addEventListener('kaidra:route-change',async e=>{if(e.detail.view==='sports'&&await account)openSports(e.detail);});
document.addEventListener('kaidra:sports-updated',()=>{const route=parseRoute(location.hash);if(route.category==='sports')renderSportsHub(route);});
account.then(async current=>{if(!current)return;const route=parseRoute(location.hash);if(route.view==='sports')openSports(route);const settings=document.getElementById('sports-settings-modal')?.querySelector('.modal-card');settings?.append(button('Supported-club notification preferences',openSportsPreferences));});
