import {getSignedMediaUrl} from './supabase-client.js';
import {element,avatar,iconButton} from './ui.js';
import {icon} from './icons.js';
const players=new Set();
const stamp=seconds=>`${Math.floor(Math.max(0,seconds)/60)}:${String(Math.floor(Math.max(0,seconds)%60)).padStart(2,'0')}`;
export function voicePlayer(message,sender={}) {
  const root=element('div','voice-message'),play=iconButton('play','Play voice note'),body=element('div','voice-message-body'),wave=element('div','voice-wave'),canvas=element('canvas'),seek=element('input','voice-seek'),meta=element('div','voice-meta'),time=element('span','voice-time',stamp(message.media_duration_seconds||0)),speed=element('button','voice-speed','1×'),photo=avatar(sender||{},'voice-avatar'),audio=element('audio');
  canvas.width=320;canvas.height=44;canvas.setAttribute('aria-hidden','true');seek.type='range';seek.min='0';seek.max=String(message.media_duration_seconds||180);seek.step='0.1';seek.value='0';seek.setAttribute('aria-label','Seek voice note');seek.disabled=true;audio.preload='none';audio.setAttribute('aria-label','Voice note audio');audio.className='hidden';speed.type='button';speed.setAttribute('aria-label','Playback speed 1×');wave.append(canvas,seek);meta.append(time,speed);body.append(wave,meta);root.append(play,body,photo,audio);let loaded,peaks=null,failed=false;
  function draw(){const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,320,44);const duration=Number.isFinite(audio.duration)?audio.duration:Number(message.media_duration_seconds||0),ratio=duration?audio.currentTime/duration:0;if(peaks){for(let i=0;i<peaks.length;i++){const height=Math.max(3,peaks[i]*38);ctx.fillStyle=i/peaks.length<=ratio?'#b7a0ff':'#747986';ctx.fillRect(i*5,22-height/2,3,height);}}else{ctx.fillStyle='#626a76';ctx.fillRect(0,21,320,2);}wave.style.setProperty('--voice-progress',`${ratio*100}%`);}
  async function load(){if(!loaded)loaded=(async()=>{const url=message.localVoiceUrl||await getSignedMediaUrl('voice-notes',message.media_url||message.content);if(!url)throw new Error('Voice note unavailable');audio.src=url;audio.load();return url;})();return loaded;}
  async function waveform(url){try{const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;const bytes=await (await fetch(url)).arrayBuffer();if(bytes.byteLength>10*1024*1024)return;const ctx=new Context();try{const decoded=await ctx.decodeAudioData(bytes),samples=decoded.getChannelData(0);peaks=Array.from({length:64},(_,i)=>{const start=Math.floor(i*samples.length/64),end=Math.floor((i+1)*samples.length/64);let max=0;for(let j=start;j<end;j+=Math.max(1,Math.floor((end-start)/300)))max=Math.max(max,Math.abs(samples[j]));return max;});draw();}finally{await ctx.close();}}catch{/* The seek control remains usable if the browser cannot decode a waveform. */}}
  play.addEventListener('click',async()=>{if(!audio.paused){audio.pause();return;}play.disabled=true;try{const url=await load();for(const other of players)if(other!==audio)other.pause();players.add(audio);await audio.play();if(!peaks)waveform(url);}catch{loaded=null;failed=true;time.textContent='Tap to retry';play.setAttribute('aria-label','Retry voice note');}finally{play.disabled=false;}});
  audio.addEventListener('play',()=>{failed=false;play.replaceChildren(icon('pause'));play.setAttribute('aria-label','Pause voice note');});
  for(const event of ['pause','ended'])audio.addEventListener(event,()=>{play.replaceChildren(icon('play'));play.setAttribute('aria-label','Play voice note');if(event==='ended')players.delete(audio);});
  audio.addEventListener('loadedmetadata',()=>{if(Number.isFinite(audio.duration))seek.max=String(audio.duration);seek.disabled=false;draw();});audio.addEventListener('timeupdate',()=>{seek.value=String(audio.currentTime);seek.setAttribute('aria-valuetext',stamp(audio.currentTime));time.textContent=stamp(audio.currentTime)+' / '+stamp(Number.isFinite(audio.duration)?audio.duration:message.media_duration_seconds||0);draw();});
  seek.addEventListener('input',()=>{audio.currentTime=Number(seek.value);draw();});speed.addEventListener('click',()=>{audio.playbackRate=audio.playbackRate===1?1.5:audio.playbackRate===1.5?2:1;speed.textContent=audio.playbackRate+'×';speed.setAttribute('aria-label','Playback speed '+speed.textContent);});audio.addEventListener('error',()=>{if(!failed){failed=true;time.textContent='Tap to retry';loaded=null;}});draw();return root;
}
document.addEventListener('kaidra:close-chat',()=>{for(const audio of players)audio.pause();players.clear();});
window.addEventListener('pagehide',()=>{for(const audio of players)audio.pause();players.clear();});

new MutationObserver(()=>{for(const audio of players)if(!audio.isConnected){audio.pause();players.delete(audio);}}).observe(document.body,{childList:true,subtree:true});
