import http from 'node:http';
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
const root=resolve(import.meta.dirname,'..');
const server=http.createServer(async(req,res)=>{
  const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);
  if(!path.startsWith(root+'/')){res.writeHead(403);return res.end();}
  try{
    let body=await readFile(path);
    if(path.endsWith('/js/supabase-client.js'))body=Buffer.from(body.toString().replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm','/tests/mock-supabase.js'));
    res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'})[extname(path)]||'text/plain');res.end(body);
  }catch{res.writeHead(404);res.end('Not found');}
});
await new Promise((done,reject)=>{server.once('error',reject);server.listen(8765,'127.0.0.1',done);});
let browserProcess;
const browserDir = await mkdtemp('/tmp/kaidra-test-browser-');
try { await fetch('http://127.0.0.1:9222/json'); }
catch {
  browserProcess = spawn('google-chrome',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--remote-debugging-port=9222',`--user-data-dir=${browserDir}`,'about:blank'],{stdio:'ignore'});
  const start=Date.now(); while(true) { try { await fetch('http://127.0.0.1:9222/json'); break; } catch { if(Date.now()-start>10000) throw new Error('Chrome did not start'); await new Promise(resolve=>setTimeout(resolve,100)); } }
}
const tabs=await(await fetch('http://127.0.0.1:9222/json')).json();
const tab=tabs.find(tab=>tab.type==='page');
const ws=new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((done,reject)=>{ws.onopen=done;ws.onerror=reject;});
let seq=0;const pending=new Map(),errors=[];
ws.onmessage=({data})=>{const value=JSON.parse(data);if(value.id){const item=pending.get(value.id);pending.delete(value.id);if(value.error)item.reject(value.error);else item.resolve(value.result);}else if(value.method==='Runtime.exceptionThrown')errors.push(value.params.exceptionDetails.exception?.description||value.params.exceptionDetails.text);};
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Browser command timed out: '+method));},20000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
async function perform(expression){return evaluate(`(async()=>{${expression}})()`);}
async function wait(expression){const start=Date.now();while(Date.now()-start<10000){if(await evaluate(`(()=>{try{return Boolean(${expression})}catch{return false}})()`))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timed out: '+expression);}
const clickText=(selector,text)=>evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(node=>node.textContent.trim()===${JSON.stringify(text)}).click()`);
const click=(selector)=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);

async function screenshot(name) { await new Promise(resolve=>setTimeout(resolve,350)); await evaluate('document.querySelector("#app-status")?.classList.add("hidden")'); await mkdir('/tmp/kaidra-qa',{recursive:true}); await writeFile('/tmp/kaidra-qa/'+name+'.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64')); }
async function size(width,height=900) { await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700}); }
async function route(tab) { await evaluate("document.dispatchEvent(new CustomEvent('kaidra:navigate',{detail:{tab:"+JSON.stringify(tab)+"}}))"); await new Promise(r=>setTimeout(r,80)); }
async function send(text) { await evaluate("document.querySelector('#message-text-input').value="+JSON.stringify(text)+";document.querySelector('#message-text-input').dispatchEvent(new Event('input'));document.querySelector('#message-form').requestSubmit()"); await wait('!document.querySelector(".is-sending")'); }
try {
 await call('Runtime.enable');await call('Page.enable');await call('Network.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});await call('Network.setBlockedURLs',{urls:['*fonts.googleapis.com*','*fonts.gstatic.com*']});await call('Storage.clearDataForOrigin',{origin:'http://127.0.0.1:8765',storageTypes:'all'});await size(390,844);
 await call('Page.navigate',{url:'http://127.0.0.1:8765/app.html#home'});await wait('window.__mock && document.querySelector("#profile-display-name").textContent==="Josh"');
 await perform('window.__mock.db.battle_identities=window.__mock.db.battle_identities.filter(i=>i.user_id!==window.__mock.me);window.__mock.db.battle_stats=[{user_id:window.__mock.me,xp:245,battles:6,wins:3,losses:2,draws:1,streak:0,best_streak:3}];window.__mock.persist()');assert.equal(await evaluate('document.querySelector(".awakening-dialog")'),null);
 await route('user/'+await evaluate('window.__mock.alice'));await wait('document.querySelector("#user-profile-social .class-identity")');assert.equal(await evaluate('document.querySelector("#user-profile-social .battle-progression")'),null);assert(!await evaluate('document.querySelector("#user-profile-social").textContent.includes("XP")'));
 await perform('window.__mock.spectatorBattle=crypto.randomUUID();window.__mock.db.battles.push({id:window.__mock.spectatorBattle,type:"direct",status:"pending",topic:"Friendly battle",conversation_id:window.__mock.a,challenger_id:window.__mock.alice,challenged_id:window.__mock.bob})');await route('battle/'+await evaluate('window.__mock.spectatorBattle'));await wait('document.querySelector(".battle-modal")');assert.equal(await evaluate('document.querySelector(".awakening-dialog")'),null);await click('.battle-modal .modal-heading button');
 await route('profile');await wait('[...document.querySelectorAll("#profile-social button")].some(b=>b.textContent.includes("Begin battle journey"))');await clickText('#profile-social button','Begin battle journey');await wait('document.querySelector(".awakening-intro")');assert(await evaluate('document.querySelector(".awakening-intro").textContent.includes("YOUR RESULT IS PERMANENT")'));assert(!await evaluate('/Choose Warrior|Choose Ninja|Retake/.test(document.querySelector(".awakening-intro").textContent)'));await screenshot('awakening-intro-mobile');
 await clickText('.awakening-dialog button','Begin determination');await wait('document.querySelector(".awakening-question-form")');assert.equal(await evaluate('document.querySelectorAll(".awakening-answer").length'),5);assert(!await evaluate('/Warrior|Wizard|Ninja|Guardian|Rogue|POWER|STRATEGY/.test(document.querySelector(".awakening-answers").textContent)'));
 // Native radio keyboard navigation and a visible checkmark accompany selection.
 await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await call('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowDown',code:'ArrowDown',windowsVirtualKeyCode:40});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowDown',code:'ArrowDown',windowsVirtualKeyCode:40});await wait('document.querySelector(".awakening-answer input:checked")');assert.equal(await evaluate('getComputedStyle(document.querySelector(".awakening-answer:has(input:checked) .awakening-choice-mark")).opacity'),'1');
 async function answer(){const previous=await evaluate('window.__mock.db.awakening_session.answers.length');await evaluate('document.querySelector(".awakening-answer input").click();document.querySelector(".awakening-question-form").requestSubmit()');await wait(`window.__mock.db.awakening_session.answers.length===${previous+1}`);await wait('document.querySelector(".awakening-question-form") || document.querySelector(".awakening-reveal") || document.querySelector(".awakening-evaluating")');}
 for(let i=0;i<5;i++)await answer();assert(await evaluate('document.querySelector(".awakening-body").scrollWidth<=document.querySelector(".awakening-body").clientWidth+1'));assert(await evaluate('[...document.querySelectorAll(".awakening-answer")].every(n=>n.getBoundingClientRect().height>=48&&n.querySelector("input").getBoundingClientRect().width<=20)'));await screenshot('awakening-question-mobile');for(const [width,height]of [[320,568],[844,390],[768,1024],[1366,900]]){await size(width,height);assert(await evaluate('document.querySelector(".awakening-body").scrollWidth<=document.querySelector(".awakening-body").clientWidth+1'));assert(await evaluate('[...document.querySelectorAll(".awakening-answer")].every(n=>n.getBoundingClientRect().height>=48)'));}await size(390,844);await click('.awakening-dialog .modal-heading button');await wait('!document.querySelector(".awakening-dialog")');await call('Page.reload');await wait('window.__mock && document.querySelector("#profile-social .battle-progression")');assert.equal(await evaluate('window.__mock.db.awakening_session.answers.length'),5);
 await clickText('#profile-social button','Begin battle journey');await wait('document.querySelector(".awakening-intro")');await clickText('.awakening-dialog button','Resume determination');await wait('document.querySelector(".awakening-kicker").textContent.includes("QUESTION 6 OF 12")');
 for(let i=5;i<12;i++)await answer();await wait('document.querySelector(".awakening-kicker").textContent.includes("QUESTION 13 OF 14")');assert(!await evaluate('/tied|probability|score/i.test(document.querySelector(".awakening-body").textContent)'));await answer();await answer();await wait('document.querySelector(".awakening-reveal")');assert.equal(await evaluate('window.__mock.db.battle_identities.find(i=>i.user_id===window.__mock.me).class_id'),'ninja');assert.equal(await evaluate('document.querySelector(".awakening-question-form")'),null);await wait('!document.querySelector(".awakening-reveal .awakening-primary").disabled');await screenshot('awakening-ninja-reveal-mobile');
 // Closing after assignment does not restart the exam; it restores only the final identity.
 await click('.awakening-dialog .modal-heading button');await perform('void (await import("/js/awakening.js")).awakenBattleIdentity()');await wait('document.querySelector(".awakening-reveal")');assert.equal(await evaluate('document.querySelector(".awakening-question-form")'),null);await clickText('.awakening-dialog button','Accept destiny');await wait('!document.querySelector(".awakening-dialog")');await wait('document.querySelector("#profile-social .class-identity strong").textContent==="Ninja"');await wait('document.querySelector("#profile-social .battle-progression").textContent.includes("245 XP")');await screenshot('awakening-private-profile-mobile');
 const begins=await evaluate('window.__mock.calls.filter(c=>c.name==="kaidra_awakening_begin").length');await clickText('#profile-social button','Your battle history');await wait('document.querySelector(".battle-history")');assert.equal(await evaluate('document.querySelector(".awakening-dialog")'),null);assert.equal(await evaluate('window.__mock.calls.filter(c=>c.name==="kaidra_awakening_begin").length'),begins);await click('.social-modal .modal-heading button');
 // Isolated fixture identities exercise each class's visual language; no production reroll exists.
 for(const id of ['warrior','wizard','ninja','guardian','rogue']){await perform(`window.__mock.db.battle_identities.find(i=>i.user_id===window.__mock.me).class_id=${JSON.stringify(id)};window.__mock.db.battle_identities.find(i=>i.user_id===window.__mock.me).acknowledged=false;void (await import('/js/awakening.js')).awakenBattleIdentity()`);await wait(`document.querySelector('.awakening-body')?.dataset.class===${JSON.stringify(id)}`);assert.equal(await evaluate('document.querySelector(".awakening-stage .class-emblem").getAttribute("viewBox")'),'0 0 64 64');await evaluate('document.querySelector(".awakening-reveal").classList.add("is-revealing")');await new Promise(r=>setTimeout(r,1700));await screenshot('awakening-'+id+'-visual');await clickText('.awakening-dialog button','Accept destiny');await wait('!document.querySelector(".awakening-dialog")');}
 await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await perform('window.__mock.db.battle_identities.find(i=>i.user_id===window.__mock.me).acknowledged=false;void (await import("/js/awakening.js")).awakenBattleIdentity()');await wait('document.querySelector(".awakening-reveal")');assert.equal(await evaluate('getComputedStyle(document.querySelector(".awakening-stage .class-emblem")).animationName'),'none');
 for(const [width,height]of [[320,568],[390,844],[844,390],[768,1024],[1366,900]]){await size(width,height);await new Promise(r=>setTimeout(r,80));assert(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'));assert(await evaluate('(()=>{const b=document.querySelector(".awakening-dialog .social-modal-card").getBoundingClientRect();return b.left>=0&&b.right<=innerWidth+1&&b.top>=0&&b.bottom<=innerHeight+1})()'));}
 await clickText('.awakening-dialog button','Accept destiny');await wait('!document.querySelector(".awakening-dialog")');await size(390,844);await route('user/'+await evaluate('window.__mock.alice'));await wait('document.querySelector("#user-profile-social .class-identity")');assert.equal(await evaluate('document.querySelector("#user-profile-social .battle-progression")'),null);
 assert.deepEqual(errors,[]);console.log('PASS Awakening browser: explicit entry, no spectator/signup trigger, private/public profile split, keyboard answers, reload/resume, bounded determinants, assigned-before-ack, no repeat exam, five SVG reveals, reduced motion and mobile/tablet/desktop/landscape bounds.');
} catch(error){console.error(error);console.error('Runtime errors:',errors);process.exitCode=1;}
finally{ws.close();server.close();browserProcess?.kill();}
