begin;
create function pg_temp.assert_ok(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',label;end if;end $$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or raise_exception or undefined_column or undefined_function then return;end;raise exception using errcode='XX000',message='Unexpected permission: '||statement;end $$;
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();sid uuid;cid uuid;bid uuid;state jsonb;resumed jsonb;first_question text;first_answer text;old_class text;answered_steps integer:=0;i integer;begin
 insert into auth.users(id,email,created_at) select id,id||'@example.invalid',now()-interval '30 days' from unnest(array[a,b]) id;
 insert into public.profiles(id,username,display_name) select id,'qa_'||left(replace(id::text,'-',''),20),'QA awakening' from unnest(array[a,b]) id;
 insert into public.battle_stats(user_id,xp,battles,wins,losses,streak) values(a,125,3,2,1,2);
 insert into public.friend_requests(requester_id,target_id,status) values(a,b,'accepted');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';
 state:=public.kaidra_awakening_begin();sid:=(state->>'session_id')::uuid;
 perform pg_temp.assert_ok(state->>'total'='12' and state->>'answered'='0','Incorrect initial exam length');
 perform pg_temp.assert_ok(not(state::text like '%weights%') and not(state::text like '%score%'),'Scoring weights leaked');
 resumed:=public.kaidra_awakening_begin();perform pg_temp.assert_ok(resumed=state,'Begin rerandomized the frozen questions');
 perform pg_temp.denied('select * from public.awakening_questions');perform pg_temp.denied('select * from public.awakening_sessions');
 perform pg_temp.denied('select public.kaidra_awakening_score(''[]'',''{}'')');
 perform pg_temp.denied(format('select public.kaidra_awakening_finalize(%L)',sid));
 perform pg_temp.denied(format('select public.kaidra_awakening_finalize(%L,''ninja'')',sid));
 perform pg_temp.denied(format('select public.kaidra_battle_create(public.get_or_create_conversation(%L),%L,''Friendly'','''',''{"entry_type":"direct"}'')',b,b));
 perform pg_temp.denied(format('select public.kaidra_awakening_answer(%L,''invented-question'',''invented-answer'')',sid));
 perform pg_temp.denied(format('select public.kaidra_awakening_answer(%L,%L,''invented-answer'')',sid,state->'question'->>'id'));
 perform pg_temp.denied(format('insert into public.battle_identities(user_id,class_id,determination_version) values(%L,''ninja'',1)',a));
 perform pg_temp.denied(format('update public.profiles set is_banned=true where id=%L',a));
 perform pg_temp.denied(format('update public.profiles set id=%L where id=%L',b,a));
 perform pg_temp.denied(format('update public.profiles set class_id=''ninja'' where id=%L',a));
 perform pg_temp.denied('truncate public.profiles');
 update public.profiles set bio='Legitimate profile edit',display_name='Still editable' where id=a;
 perform pg_temp.assert_ok((select bio='Legitimate profile edit' from public.profiles where id=a),'Legitimate profile editing broke');
 first_question:=state->'question'->>'id';first_answer:=state->'question'->'options'->0->>'id';
 state:=public.kaidra_awakening_answer(sid,first_question,first_answer);
 resumed:=public.kaidra_awakening_answer(sid,first_question,first_answer);
 perform pg_temp.assert_ok(state=resumed and state->>'answered'='1','Retry counted a decision twice');
 perform pg_temp.denied(format('select public.kaidra_awakening_answer(%L,%L,''different-answer'')',sid,first_question));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform pg_temp.denied(format('select public.kaidra_awakening_answer(%L,%L,%L)',sid,state->'question'->>'id',state->'question'->'options'->0->>'id'));
 perform pg_temp.assert_ok(public.kaidra_profile_social(a)->'stats'='null'::jsonb,'Foreign progression leaked from profile RPC');
 perform pg_temp.assert_ok(not exists(select 1 from public.battle_stats where user_id=a),'Foreign raw stats leaked');
 perform pg_temp.denied(format('select public.kaidra_profile_social_internal(%L)',a));
 execute 'reset role';update public.awakening_sessions set expires_at=now()-interval '1 second' where id=sid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';
 perform pg_temp.denied(format('select public.kaidra_awakening_answer(%L,%L,%L)',sid,state->'question'->>'id',state->'question'->'options'->0->>'id'));
 state:=public.kaidra_awakening_begin();perform pg_temp.assert_ok(state->>'session_id'=sid::text and state->>'answered'='1','Expiry resume rerolled or discarded progress');
 while state->'identity'='null'::jsonb loop
  answered_steps:=answered_steps+1;if answered_steps>13 then raise exception 'Determination exceeded 14 questions';end if;
  state:=public.kaidra_awakening_answer(sid,state->'question'->>'id',state->'question'->'options'->0->>'id');
 end loop;
 old_class:=state->'identity'->>'class_id';perform pg_temp.assert_ok(old_class in('warrior','wizard','ninja','guardian','rogue','healer','ranger','berserker'),'Invalid permanent result');
 perform pg_temp.assert_ok((public.kaidra_awakening_finalize(sid)->'identity'->>'class_id')=old_class,'Finalize retry changed class');
 perform pg_temp.assert_ok(public.kaidra_awakening_begin()->'question'='null'::jsonb,'Completed account received another exam');
 perform pg_temp.assert_ok(public.kaidra_awakening_progress()->'identity'->>'class_id'=old_class,'Progress lookup did not restore the permanent identity');
 perform pg_temp.assert_ok(public.kaidra_battle_identity()->>'acknowledged'='false','Assignment waited for acknowledgement');
 perform public.kaidra_awakening_acknowledge();perform public.kaidra_awakening_acknowledge();
 perform pg_temp.assert_ok(public.kaidra_battle_identity()->>'acknowledged'='true','Destiny acknowledgement did not persist');
 perform pg_temp.denied(format('update public.battle_identities set class_id=''wizard'' where user_id=%L',a));
 perform pg_temp.denied(format('delete from public.battle_identities where user_id=%L',a));
 perform pg_temp.assert_ok(public.kaidra_profile_social(a)->'stats'->>'xp'='125','Owner private progression disappeared');
 cid:=public.get_or_create_conversation(b);bid:=public.kaidra_battle_create(cid,b,'Ready?','',jsonb_build_object('entry_type','direct'));
 perform pg_temp.assert_ok(exists(select 1 from jsonb_array_elements(public.kaidra_battle_state(bid)->'participants') p where p->>'id'=a::text and p->'identity'->>'class_id'=old_class),'Challenge lost the permanent class identity');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform pg_temp.denied(format('select public.kaidra_battle_action(%L,''accept'')',bid));
 perform pg_temp.assert_ok(public.kaidra_battle_identity(a)->>'class_id'=old_class,'Public identity missing');
 perform pg_temp.denied(format('update public.battle_identities set class_id=''rogue'' where user_id=%L',a));
 execute 'reset role';
 perform pg_temp.assert_ok((select jsonb_array_length(questions) in(12,14) and completed_at is not null and result_class=old_class and score_audit is not null from public.awakening_sessions where user_id=a),'Private assignment audit is incomplete');
 -- Even a privileged generic update cannot silently replace the existing result.
 perform pg_temp.denied(format('update public.battle_identities set class_id=%L where user_id=%L',case when old_class='wizard' then 'ninja' else 'wizard' end,a));
 -- Force close scores in an isolated fixture, verify two bounded pair determinants, then stable finalization.
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);execute 'set local role authenticated';state:=public.kaidra_awakening_begin();sid:=(state->>'session_id')::uuid;execute 'reset role';
 update public.awakening_sessions set questions=(select jsonb_agg(q||jsonb_build_object('options',(select jsonb_agg(o||jsonb_build_object('weights','[2,2,2,2,2]'::jsonb)) from jsonb_array_elements(q->'options') o))) from jsonb_array_elements(questions) q) where id=sid;
 execute 'set local role authenticated';state:=public.kaidra_awakening_begin();
 for i in 1..12 loop state:=public.kaidra_awakening_answer(sid,state->'question'->>'id',state->'question'->'options'->0->>'id');end loop;
 perform pg_temp.assert_ok(state->>'total'='14' and state->'identity'='null'::jsonb,'Close scores did not add exactly two determinant scenarios');
 for i in 1..2 loop state:=public.kaidra_awakening_answer(sid,state->'question'->>'id',state->'question'->'options'->0->>'id');end loop;
 perform pg_temp.assert_ok(state->'identity'->>'class_id' is not null and state->>'total'='14','Tie resolution did not finish');
 perform public.kaidra_battle_action(bid,'accept');
 perform pg_temp.assert_ok((select status='active' from public.battles where id=bid),'Awakened target could not accept challenge');
 execute 'reset role';
 insert into public.battle_rewards(battle_id,user_id,opponent_id,xp) values(bid,a,b,25),(bid,b,a,5);
 execute 'set local role authenticated';
 perform pg_temp.assert_ok(jsonb_array_length(public.kaidra_battle_state(bid)->'rewards')=1 and public.kaidra_battle_state(bid)->'rewards'->0->>'user_id'=b::text,'Challenge state exposed another participant reward');
 execute 'reset role';
end $$;
rollback;
