begin;
create function pg_temp.check_ok(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',label;end if;end $$;
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();cid uuid;gid uuid;legacy uuid:=gen_random_uuid();bid uuid:=gen_random_uuid();newbid uuid;detail text;begin
 insert into auth.users(id,email,created_at) select u,u||'@example.invalid',now()-interval '30 days' from unnest(array[a,b,c]) u;
 insert into public.profiles(id,username,display_name) select u,'qa_'||left(replace(u::text,'-',''),16),'QA creation member' from unnest(array[a,b,c]) u;
 insert into public.battle_identities(user_id,class_id,determination_version) values(a,'ninja',1),(b,'warrior',1);
 insert into public.friend_requests(requester_id,target_id,status) values(a,b,'accepted');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 execute 'set local role authenticated';cid:=public.get_or_create_conversation(b);gid:=public.kaidra_create_group('QA creation',array[b]);execute 'reset role';
 insert into public.battles(id,conversation_id,challenger_id,challenged_id,type,topic,challenger_position,combat_version,status,ends_at) values(legacy,cid,a,b,'direct','Friendly battle',null,0,'active',now()+interval '1 day');
 execute 'set local role authenticated';
 begin perform public.kaidra_battle_create(cid,b,'','', '{"entry_type":"direct"}',bid);raise exception using errcode='XX000',message='Legacy challenge silently overwritten';exception when raise_exception then get stacked diagnostics detail=pg_exception_detail;perform pg_temp.check_ok(detail::jsonb->>'battle_id'=legacy::text,'Legacy conflict link missing');end;
 perform pg_temp.check_ok((select status='active' from public.battles where id=legacy),'Legacy record changed without participant action');
 perform public.kaidra_battle_action(legacy,'close_legacy');perform public.kaidra_battle_action(legacy,'close_legacy');
 perform pg_temp.check_ok((select status='cancelled' from public.battles where id=legacy),'Participant could not close old invitation');
 perform public.kaidra_battle_create(cid,b,'','', '{"entry_type":"direct"}',bid);
 begin perform public.kaidra_battle_action(bid,'close_legacy');raise exception using errcode='XX000',message='Legacy closure ended real RPG battle';exception when raise_exception then null;end;
 perform pg_temp.check_ok(public.kaidra_battle_create(cid,b,'','', '{"entry_type":"direct"}',bid)=bid,'Retry changed battle');
 begin perform public.kaidra_battle_create(gid,b,'','', '{"entry_type":"direct"}');raise exception using errcode='XX000',message='Concurrent pair allowed';exception when raise_exception then get stacked diagnostics detail=pg_exception_detail;perform pg_temp.check_ok(detail::jsonb->>'battle_id'=bid::text,'Conflict did not expose accessible existing battle');end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',c,'role','authenticated')::text,true);
 begin perform public.kaidra_battle_create(cid,b,'','', '{"entry_type":"direct"}');raise exception using errcode='XX000',message='Outsider could create battle';exception when raise_exception then get stacked diagnostics detail=pg_exception_detail;perform pg_temp.check_ok(coalesce(detail,'') not like '%'||bid||'%','Outsider learned existing battle');end;
 execute 'reset role';update public.battles set created_at=now()-interval '11 minutes' where id=bid;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';newbid:=public.kaidra_battle_create(gid,b,'','', '{"entry_type":"direct"}');
 perform pg_temp.check_ok(newbid<>bid and (select status='expired' from public.battles where id=bid),'Cross-chat pending expiry failed');
 perform pg_temp.check_ok(not exists(select 1 from public.battle_rewards where battle_id in(bid,legacy)),'Expired invitations awarded XP');execute 'reset role';
 perform pg_temp.check_ok(has_function_privilege('authenticated','public.kaidra_battle_create(uuid,uuid,text,text,jsonb,uuid)','execute') and not has_function_privilege('anon','public.kaidra_battle_create(uuid,uuid,text,text,jsonb,uuid)','execute'),'Creation auth boundary changed');
 perform pg_temp.check_ok(not has_function_privilege('authenticated','public.kaidra_battle_create_preexpiry(uuid,uuid,text,text,jsonb,uuid)','execute'),'Creation guard bypass exposed');
 perform pg_temp.check_ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='battles_open_pair_idx') and exists(select 1 from pg_indexes where schemaname='public' and indexname='battle_one_open_conversation'),'Open battle constraints removed');
end $$;
rollback;
