import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
const source=readFileSync('supabase/functions/_shared/browse.ts','utf8').replace("import { cached, upstream, allowedUrl } from './content.ts';",'const allowedUrl=value=>value;').replace("import { animeBrowse, animeMeta } from './anime.ts';",'');
const {browse,browseMeta}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const calls=[];
const anime=async(path,params)=>{calls.push({path,params});if(path==='/seasons')return {data:[{year:2030,seasons:['winter']},{year:1978,seasons:['summer']}]};if(path==='/genres/anime')return {data:params.filter==='themes'?[{mal_id:40,name:'Psychological'},{mal_id:19,name:'Music'}]:[{mal_id:7,name:'Mystery'},{mal_id:12,name:'Hentai'}]};return {pagination:{has_next_page:true},data:[{mal_id:1,title:'Real provider fixture',genres:[{mal_id:7,name:'Mystery'}],themes:[{mal_id:40,name:'Psychological'},{mal_id:19,name:'Music'}],images:{},score:8},{mal_id:2,title:'Adult',genres:[{mal_id:12,name:'Hentai'}],images:{}}]};};
const tmdb=async(path,params)=>{calls.push({path,params});return {total_pages:3,results:[{id:1,title:'Movie',adult:false},{id:2,title:'Adult',adult:true}]};};
const meta=await browseMeta('anime',tmdb,anime);assert.deepEqual(meta.years.map(y=>y.year),[2030,1978]);assert.equal(meta.genres.length,1);assert.equal(meta.themes.length,2);
const archive=await browse({category:'anime',year:2026,season:'fall',genre:7,theme:40,sort:'rating',page:2},tmdb,anime);assert.equal(archive.items.length,1);assert.equal(calls.at(-1).path,'/seasons/2026/fall');assert.deepEqual(calls.at(-1).params,{page:'2',limit:'24',sfw:'true'});assert(archive.context.includes('each loaded page'));assert(archive.hasMore);
await browse({category:'anime',year:2050,season:'winter'},tmdb,anime);assert.equal(calls.at(-1).path,'/seasons/2050/winter');
await browse({category:'anime',genre:7,theme:40},tmdb,anime);assert.equal(calls.at(-1).params.genres,'7,40');
await browse({category:'movie',cinema:'NG',format:'animation',genre:28,year:1999,sort:'rating'},tmdb);assert.equal(calls.at(-1).params.with_origin_country,'NG');assert.equal(calls.at(-1).params.with_genres,'28,16');assert.equal(calls.at(-1).params['vote_count.gte'],'100');assert.equal(calls.at(-1).params['primary_release_date.gte'],'1999-01-01');
await browse({category:'movie',cinema:'IN'},tmdb);assert.equal(calls.at(-1).params.with_original_language,'hi');
await browse({category:'tv',section:'completed',service:8,region:'NG'},tmdb);assert.equal(calls.at(-1).params.with_status,'3|4');assert.equal(calls.at(-1).params.watch_region,'NG');
await browse({category:'movie',query:'all tastes',genre:28},tmdb);assert.equal(calls.at(-1).path,'/search/movie');assert(!calls.at(-1).params.with_genres);
assert.equal((await browse({category:'anime',year:1980},tmdb,anime)).items.length,0);
await assert.rejects(()=>browse({category:'games'},tmdb),RangeError);await assert.rejects(()=>browse({category:'movie',page:0},tmdb),RangeError);
console.log('Provider browse checks passed: dynamic archives, overlapping genres/themes, safe content, seasons, origins/formats, TV services/status, independent search and pagination.');
