import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
const {kits,resolveCombat}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(readFileSync('supabase/functions/_shared/combat.ts','utf8'))).toString('base64'));
export function state(classes){return {id:'test',phase:'playing',active_id:'u0',turn:1,round:1,revision:1,deadline:new Date(Date.now()+25000).toISOString(),seed:'server-private-test-seed',winning_team:null,fighters:classes.map((class_id,i)=>({user_id:'u'+i,team:i<classes.length/2?1:2,class_id,hp:kits[class_id].hp,max_hp:kits[class_id].hp,resource:kits[class_id].start,turn_order:i+1,turns:0,timeouts:0,ready:true})),effects:[],cooldowns:[]};}
const intent=(s,ability,target,actor=s.active_id)=>({actor,ability,target,request_id:'test-'+s.revision,expected_revision:s.revision});
const base=state(['warrior','wizard']);assert.throws(()=>resolveCombat(base,intent(base,'slash','u0')),e=>e.code==='INVALID_TARGET');assert.throws(()=>resolveCombat(base,intent(base,'arcane_bolt','u1')),e=>e.code==='INVALID_ABILITY');assert.throws(()=>resolveCombat(base,intent(base,'arcane_bolt','u0','u1')),e=>e.code==='NOT_YOUR_TURN');assert.throws(()=>resolveCombat(base,{...intent(base,'slash','u1'),expected_revision:0}),e=>e.code==='STALE_TURN');
assert.deepEqual(resolveCombat(base,intent(base,'slash','u1'),1000),resolveCombat(base,intent(base,'slash','u1'),1000));assert.equal(base.fighters[1].hp,100,'Resolver mutated the input');
const rich=state(['wizard','warrior']);const cast=resolveCombat(rich,intent(rich,'arcane_burst','u1')).state;assert(cast.effects.some(e=>e.kind==='casting'));const castResolved=resolveCombat(cast,intent(cast,'slash','u0'));assert(castResolved.events.some(e=>e.kind==='damage'&&e.source==='u0'));assert(!castResolved.state.effects.some(e=>e.kind==='casting'));
const interrupted=state(['wizard','guardian']);const waiting=resolveCombat(interrupted,intent(interrupted,'arcane_burst','u1')).state;const disrupted=resolveCombat(waiting,intent(waiting,'shield_bash','u0'));assert(!disrupted.state.effects.some(e=>e.kind==='casting'));assert(!disrupted.events.some(e=>e.kind==='damage'&&e.source==='u0'));
const protectedState=state(['guardian','healer','ninja','wizard']);let shield=resolveCombat(protectedState,intent(protectedState,'protect','u1')).state;shield.active_id='u2';const intercept=resolveCombat(shield,intent(shield,'shadow_strike','u1'));assert(intercept.events.some(e=>e.kind==='intercept'));assert(intercept.state.fighters[0].hp<125);assert(intercept.state.fighters[1].hp<105);
const ally=state(['healer','warrior','rogue','ranger']);ally.fighters[1].hp=70;const restored=resolveCombat(ally,intent(ally,'restoration','u1'));assert(restored.state.fighters[1].hp>70);assert.throws(()=>resolveCombat(ally,intent(ally,'restoration','u2')),e=>e.code==='INVALID_TARGET');
const teamConcede=resolveCombat(ally,{...intent(ally,'','u0'),action:'surrender'});assert.equal(teamConcede.state.phase,'playing');assert.equal(teamConcede.state.fighters[0].hp,0);assert.equal(teamConcede.state.active_id,'u1');
function simulate(classes,defensive=false){let s=state(classes);for(let i=0;i<250&&s.phase==='playing';i++){const f=s.fighters.find(f=>f.user_id===s.active_id),enemy=s.fighters.find(t=>t.team!==f.team&&t.hp>0);let ability=defensive? kits[f.class_id].abilities.find(a=>['heal','guard','shield','regen','focus'].includes(a.kind)&&a.cost<=f.resource&&!s.cooldowns.some(c=>c.user_id===f.user_id&&c.ability_id===a.id&&c.ready_turn>f.turns)):null;
 if(!ability)ability=kits[f.class_id].abilities.find(a=>['attack','pierce','multi','exploit','execute','blood','interrupt','cast'].includes(a.kind)&&!a.condition&&a.cost<=f.resource&&!s.cooldowns.some(c=>c.user_id===f.user_id&&c.ability_id===a.id&&c.ready_turn>f.turns));const target=ability&&['self','ally'].includes(ability.target)?f.user_id:enemy.user_id;
 s=resolveCombat(s,intent(s,ability?.id||'basic',target),Date.now()).state;for(const t of s.fighters){assert(t.hp>=0&&t.hp<=t.max_hp);assert(t.resource>=0&&t.resource<=100);}}
 assert.equal(s.phase,'finished',`Unfinished ${classes} defensive=${defensive}`);return s;
}
for(const name of Object.keys(kits))simulate([name,name]);for(const a of Object.keys(kits))for(const b of Object.keys(kits))simulate([a,b]);simulate(['guardian','guardian'],true);simulate(['healer','healer'],true);
for(const classes of [['warrior','healer','ninja','wizard'],['guardian','healer','rogue','ranger'],['berserker','wizard','guardian','ninja']])simulate(classes);
const stalled=state(['guardian','guardian']);const expired=Date.parse(stalled.deadline)+1;const timed=resolveCombat(stalled,{...intent(stalled,'',''),action:'timeout'},expired);assert.equal(timed.state.fighters[0].timeouts,1);assert(timed.events.some(e=>e.kind==='turn_timeout'));assert.throws(()=>resolveCombat(stalled,{...intent(stalled,'',''),action:'timeout'},Date.now()),e=>e.code==='TURN_STILL_OPEN');
console.log('PASS eight mirror matches, all 64 class pairings, three 2v2 compositions, Guardian/Healer anti-stall, casting/interrupts, protection, ally targeting, own-fighter surrender, authoritative bounds/turns/idempotent resolution and timeouts. These are engine checks, not a claim of final competitive balance.');
