import http from 'node:http';
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
const root=resolve(import.meta.dirname,'..');
const server=http.createServer(async(req,res)=>{
  const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);
  if(!path.startsWith(root+'/')){res.writeHead(403);return res.end();}
  try{
    let body=await readFile(path);
    if(path.endsWith('/js/supabase-client.js'))body=Buffer.from(body.toString().replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm','/tests/mock-supabase.js'));
    res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'})[extname(path)]||'text/plain');res.end(body);
  }catch{res.writeHead(404);res.end('Not found');}
});
await new Promise((done,reject)=>{server.once('error',reject);server.listen(8765,'127.0.0.1',done);});
let browserProcess;
const browserDir = await mkdtemp('/tmp/kaidra-test-browser-');
try { await fetch('http://127.0.0.1:9222/json'); }
catch {
  browserProcess = spawn('google-chrome',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--remote-debugging-port=9222',`--user-data-dir=${browserDir}`,'about:blank'],{stdio:'ignore'});
  const start=Date.now(); while(true) { try { await fetch('http://127.0.0.1:9222/json'); break; } catch { if(Date.now()-start>10000) throw new Error('Chrome did not start'); await new Promise(resolve=>setTimeout(resolve,100)); } }
}
const tabs=await(await fetch('http://127.0.0.1:9222/json')).json();
const tab=tabs.find(tab=>tab.type==='page');
const ws=new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((done,reject)=>{ws.onopen=done;ws.onerror=reject;});
let seq=0;const pending=new Map(),errors=[];
ws.onmessage=({data})=>{const value=JSON.parse(data);if(value.id){const item=pending.get(value.id);pending.delete(value.id);if(value.error)item.reject(value.error);else item.resolve(value.result);}else if(value.method==='Runtime.exceptionThrown')errors.push(value.params.exceptionDetails.exception?.description||value.params.exceptionDetails.text);};
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Browser command timed out: '+method));},20000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
async function perform(expression){return evaluate(`(async()=>{${expression}})()`);}
async function wait(expression){const start=Date.now();while(Date.now()-start<10000){if(await evaluate(`(()=>{try{return Boolean(${expression})}catch{return false}})()`))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timed out: '+expression);}
const clickText=(selector,text)=>evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(node=>node.textContent.trim()===${JSON.stringify(text)}).click()`);
const click=(selector)=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);

async function screenshot(name) { await new Promise(resolve=>setTimeout(resolve,350)); await evaluate('document.querySelector("#app-status")?.classList.add("hidden")'); await mkdir('/tmp/kaidra-qa',{recursive:true}); await writeFile('/tmp/kaidra-qa/'+name+'.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64')); }
async function size(width,height=900) { await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700}); }
async function route(tab) { await evaluate("document.dispatchEvent(new CustomEvent('kaidra:navigate',{detail:{tab:"+JSON.stringify(tab)+"}}))"); await new Promise(r=>setTimeout(r,80)); }
async function send(text) { await evaluate("document.querySelector('#message-text-input').value="+JSON.stringify(text)+";document.querySelector('#message-text-input').dispatchEvent(new Event('input'));document.querySelector('#message-form').requestSubmit()"); await wait('!document.querySelector(".is-sending")'); }
try {
 await call('Runtime.enable');await call('Page.enable');await call('Emulation.setTouchEmulationEnabled',{enabled:true});await call('Network.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});await call('Network.setBlockedURLs',{urls:['*fonts.googleapis.com*','*fonts.gstatic.com*']});await call('Storage.clearDataForOrigin',{origin:'http://127.0.0.1:8765',storageTypes:'all'});await size(390,844);
 await call('Page.navigate',{url:'http://127.0.0.1:8765/app.html#inbox'});await wait('window.__mock && document.querySelector(".conversation-row")');await click('.conversation-row');await wait('document.querySelector(".message-bubble") && document.querySelector("#chat-connection-status").textContent==="Connected"');
 await click('.message-actions button[aria-label="More message actions"]');await wait('document.querySelector(".context-menu")');assert(!await evaluate('/Agree|Disagree|Challenge this take/.test(document.querySelector(".context-menu").textContent)'));await click('.context-layer .modal-heading button');
 await click('#composer-plus');await clickText('.context-action','Start discussion');await wait('!document.querySelector("#discussion-mode").classList.contains("hidden")');assert(await evaluate('document.querySelector("#message-text-input").placeholder.includes("agree or disagree")'));await send('A deliberate claim');await wait('window.__mock.db.messages.some(m=>m.message_type==="discussion"&&m.content==="A deliberate claim")');assert(await evaluate('document.querySelector("#discussion-mode").classList.contains("hidden")'));assert(!await evaluate('document.querySelector(".outgoing .discussion-choices")'));
 await send('.discuss This shortcut is a discussion');await wait('window.__mock.db.messages.some(m=>m.message_type==="discussion"&&m.content==="This shortcut is a discussion")');assert(!await evaluate('window.__mock.db.messages.some(m=>m.content.startsWith(".discuss"))'));
 await evaluate('window.__mock.incomingDiscussion=crypto.randomUUID();const m={id:window.__mock.incomingDiscussion,conversation_id:window.__mock.a,sender_id:window.__mock.alice,message_type:"discussion",content:"Gojo beats Sukuna",created_at:new Date(Date.now()+10).toISOString()};window.__mock.db.messages.push(m);window.__mock.emit("messages","INSERT",m)');await wait('document.querySelector(".incoming .discussion-choices")');assert(!await evaluate('document.querySelector(".incoming .discussion-card").textContent.includes("%")'));await clickText('.incoming .discussion-choices button','Agree');await wait('window.__mock.db.discussion_positions[0]?.position==="agree"');await clickText('.incoming .discussion-choices button','Disagree');await wait('document.querySelector(".incoming .discussion-choices button[aria-pressed=true]").textContent.includes("Disagree")');
 const mid=await evaluate('window.__mock.incomingDiscussion');await click(`[data-message-id="${mid}"] .message-actions button[aria-label="React to message"]`);await clickText('.reaction-choice','😂');await wait('window.__mock.db.message_reactions.some(r=>r.emoji==="😂")');assert.equal(await evaluate('window.__mock.db.discussion_positions.length'),1);assert.equal(await evaluate('window.__mock.db.discussion_positions[0].position'),'disagree');await wait('document.querySelector(".discussion-challenge")');await click('.discussion-challenge');await wait('document.querySelector(".challenge-dialog form")');assert.equal(await evaluate('document.querySelector(".challenge-dialog textarea")'),null);await evaluate('document.querySelector(".challenge-dialog form").requestSubmit()');await wait('window.__mock.db.battles.length===1');assert.equal(await evaluate('window.__mock.db.battles[0].type'),'discussion');assert.equal(await evaluate('window.__mock.db.battles[0].discussion_message_id'),mid);await click('.battle-modal .modal-heading button');
 await route('inbox/'+await evaluate('window.__mock.a'));await wait('document.querySelector("#chat-view-drawer").classList.contains("is-active")');await send('.challenge @alice You cannot beat me 😂');await wait('window.__mock.db.battles.length===2');assert.equal(await evaluate('window.__mock.db.battles[1].type'),'direct');assert.equal(await evaluate('window.__mock.db.battles[1].challenger_position'),'');assert(!await evaluate('window.__mock.db.messages.some(m=>m.content.startsWith(".challenge"))'));
 // A true touch gesture verifies capture, motion and reply activation on each message type.
 async function swipe(selector,dx=76,dy=0){await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);await new Promise(r=>setTimeout(r,200));const point=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return {x:r.left+Math.min(12,r.width/2),y:r.top+r.height-6}})()`);await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point]});for(let i=1;i<=4;i++){await call('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x+dx*i/4,y:point.y+dy*i/4}]});await new Promise(r=>setTimeout(r,30));}const moved=await evaluate('!!document.querySelector(".is-swiping")');await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});return moved;}
 await evaluate('document.querySelector("#message-thread-container").scrollTop=999999');assert(await swipe(`[data-message-id="${mid}"] .discussion-statement`));await wait('!document.querySelector("#share-draft-preview").classList.contains("hidden")');await click('#share-draft-preview button');
 await send('Outgoing swipe target');await wait('[...document.querySelectorAll(".outgoing .message-bubble")].some(n=>n.textContent==="Outgoing swipe target")');assert(await swipe('.outgoing:last-child .message-bubble'));await wait('document.querySelector(".reply-draft")');await send('Reply sent');await wait('document.querySelector(".outgoing .reply-quote")');await click('.outgoing .reply-quote');await wait('document.querySelector(".message-highlight")');
 await click('#composer-plus');await clickText('.context-action','Start discussion');await click('#discussion-mode-close');assert(await evaluate('document.querySelector("#discussion-mode").classList.contains("hidden")'));
 await evaluate('window.__mock.typing(window.__mock.a)');await wait('document.querySelector("#chat-typing-status").textContent.includes("typing")');await new Promise(r=>setTimeout(r,2400));assert.equal(await evaluate('document.querySelector("#chat-typing-status").textContent'),'');
 await evaluate('document.querySelector("#message-text-input").value="typing draft";document.querySelector("#message-text-input").dispatchEvent(new Event("input"))');await wait('window.__mock.typingTracks?.length>0');await new Promise(r=>setTimeout(r,3400));assert(await evaluate('window.__mock.typingStopped'));
 await call('Page.reload');await wait('document.querySelector(".incoming .discussion-choices button[aria-pressed=true]")');assert((await evaluate('document.querySelector(".incoming .discussion-choices button[aria-pressed=true]").textContent')).includes('Disagree'));assert(await evaluate('document.querySelector(".reaction-pill").textContent.includes("😂")'));

 await evaluate('window.__mock.group=crypto.randomUUID();window.__mock.groupDiscussion=crypto.randomUUID();const cid=window.__mock.group;window.__mock.db.conversations.push({id:cid,title:"Focused group",is_group:true,typing_revision:1,permissions:{send_messages:"everyone"}});window.__mock.db.conversation_participants.push(...[window.__mock.me,window.__mock.alice,window.__mock.bob].map(user_id=>({conversation_id:cid,user_id,role:"participant"})));const m={id:window.__mock.groupDiscussion,conversation_id:cid,sender_id:window.__mock.alice,content:"Group claim",message_type:"discussion",created_at:new Date().toISOString()};window.__mock.db.messages.push(m);window.__mock.db.discussion_positions.push({discussion_message_id:m.id,user_id:window.__mock.bob,position:"agree",conversation_id:cid});window.__mock.emit("messages","INSERT",m)');
 await wait('[...document.querySelectorAll(".conversation-row")].some(r=>r.textContent.includes("Focused group"))');await route('inbox/'+await evaluate('window.__mock.group'));await wait('document.querySelector(".incoming .discussion-card")');assert(!await evaluate('document.querySelector(".discussion-card").textContent.includes("%")'));await clickText('.discussion-choices button','Disagree');await wait('document.querySelector(".discussion-result").textContent.includes("Agree 50%")');await screenshot('focused-group-discussion');
 await send('Receipt transitions');await wait('document.querySelector(".outgoing .message-receipt")');assert.equal(await evaluate('document.querySelector(".outgoing .message-receipt").textContent'),'✓');
 await evaluate('window.__mock.receiptMessage=window.__mock.db.messages.find(m=>m.content==="Receipt transitions").id;const id=window.__mock.receiptMessage;for(const user_id of [window.__mock.alice,window.__mock.bob]){const receipt={message_id:id,user_id,conversation_id:window.__mock.group,delivered_at:new Date().toISOString()};window.__mock.db.message_deliveries.push(receipt);window.__mock.emit("message_deliveries","UPDATE",receipt)}');await wait('document.querySelector(".outgoing .message-receipt").textContent==="✓✓"');assert(!await evaluate('document.querySelector(".outgoing .message-receipt").classList.contains("is-read")'));
 await perform('const receipt={message_id:window.__mock.receiptMessage,user_id:window.__mock.alice,conversation_id:window.__mock.group};window.__mock.db.message_reads.push(receipt);window.__mock.emit("message_reads","INSERT",receipt)');await wait('document.querySelector(".outgoing .message-receipt").title.includes("read by 1/2")');assert(!await evaluate('document.querySelector(".outgoing .message-receipt").classList.contains("is-read")'));
 await perform('const receipt={message_id:window.__mock.receiptMessage,user_id:window.__mock.bob,conversation_id:window.__mock.group};window.__mock.db.message_reads.push(receipt);window.__mock.emit("message_reads","INSERT",receipt)');await wait('document.querySelector(".outgoing .message-receipt.is-read")');
 const group=await evaluate('window.__mock.group');await perform('window.__mock.forwardVoice=crypto.randomUUID();const m={id:window.__mock.forwardVoice,conversation_id:window.__mock.group,sender_id:window.__mock.alice,message_type:"voice_note",content:window.__mock.group+"/source.webm",media_url:window.__mock.group+"/source.webm",media_duration_seconds:2,created_at:new Date(Date.now()+20).toISOString()};window.__mock.db.messages.push(m);window.__mock.emit("messages","INSERT",m)');await wait('document.querySelector(".incoming audio.chat-media")');await click(`[data-message-id="${await evaluate('window.__mock.forwardVoice')}"] .message-actions button[aria-label="More message actions"]`);await wait('document.querySelector(".context-menu")');assert(!await evaluate('document.querySelector(".context-menu").textContent.includes("Copy text")'));await clickText('.context-action','Forward');await wait('document.querySelector("#new-chat-list .person-row")');await evaluate('[...document.querySelectorAll("#new-chat-list .person-row")].find(row=>row.textContent.includes("Alice")).click()');await wait('window.__mock.copies?.length===1');const forwarded=await evaluate('window.__mock.db.messages.find(m=>m.sender_id===window.__mock.me&&m.message_type==="voice_note")');assert.equal(forwarded.conversation_id,await evaluate('window.__mock.a'));assert(forwarded.media_url.startsWith(forwarded.conversation_id+'/'));assert(!forwarded.media_url.startsWith(group+'/'));assert.equal(forwarded.media_duration_seconds,2);
 await swipe('.outgoing .message-bubble',30,0);assert(!await evaluate('document.querySelector(".reply-draft")'));await swipe('.outgoing .message-bubble',20,80);assert(!await evaluate('document.querySelector(".reply-draft")'));
 await evaluate('for(let i=0;i<40;i++){const m={id:crypto.randomUUID(),conversation_id:window.__mock.group,sender_id:window.__mock.alice,content:"History message "+i,message_type:"text",created_at:new Date(Date.now()+i+100).toISOString()};window.__mock.db.messages.push(m)}window.__mock.reconnect()');await wait('document.querySelectorAll(".message-row").length>=40');
 await evaluate('document.querySelector("#message-thread-container").scrollTop=999999;document.querySelector("#message-text-input").blur();document.querySelector("#message-text-input").focus();Object.defineProperty(visualViewport,"height",{value:400,configurable:true});Object.defineProperty(visualViewport,"offsetTop",{value:30,configurable:true});visualViewport.dispatchEvent(new Event("resize"))');await new Promise(r=>setTimeout(r,180));
 const keyboard=await evaluate('(()=>{const f=document.querySelector("#message-form").getBoundingClientRect(),t=document.querySelector("#message-thread-container");return {bottom:f.bottom,gap:t.scrollHeight-t.scrollTop-t.clientHeight}})()');assert(keyboard.bottom<=430&&keyboard.gap<3,JSON.stringify(keyboard));
 await evaluate('document.querySelector("#message-thread-container").scrollTop=0;document.querySelector("#message-text-input").blur();document.querySelector("#message-text-input").focus()');await new Promise(r=>setTimeout(r,100));await evaluate('Object.defineProperty(visualViewport,"height",{value:330,configurable:true});visualViewport.dispatchEvent(new Event("resize"))');await new Promise(r=>setTimeout(r,120));assert(await evaluate('document.querySelector("#message-thread-container").scrollTop<10'));await screenshot('focused-chat-keyboard-history');await evaluate('delete visualViewport.height;delete visualViewport.offsetTop;visualViewport.dispatchEvent(new Event("resize"))');
 await click('#close-chat-btn');
 await route('discover/tv/popular');await wait('document.querySelector("#discover-hero .discover-backdrop")');assert.equal(await evaluate('document.querySelector(".anime-cover-art")'),null);await screenshot('focused-series-preserved');
 await route('discover/anime/popular');await wait('document.querySelector("#discover-hero .discover-backdrop")');await screenshot('focused-anime-banner');
 await perform('window.__mock.animeCoversOnly=true;(await import("/js/content-client.js")).clearContentCache()');await route('discover/anime/new');await wait('document.querySelector(".anime-cover-art .anime-hero-cover")');assert.equal(await evaluate('document.querySelector("#discover-hero .discover-backdrop")'),null);await screenshot('focused-anime-cover-fallback');
 for(const width of [320,390,768,1366]){await size(width);assert(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'));}
 assert.deepEqual(errors,[]);console.log('PASS focused browser: ordinary menus, discussion mode/command/switch/persistence/reaction, contextual/direct challenges, touch swipe/reply jump/cancellation, group split and receipt states, keyboard latest/history, typing expiry, preserved Series and anime banners, responsive widths.');
} catch(error){console.error(error);console.error('Runtime errors:',errors);process.exitCode=1;}
finally{ws.close();server.close();browserProcess?.kill();}
