-- Run on the deployed schema, or append inside migration's rolled-back dry run.
begin;
create function pg_temp.assert_ok(ok boolean, label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception '%',label; end if; end $$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$ begin
 begin execute statement; exception when insufficient_privilege or raise_exception then return; end;
 raise exception using errcode='XX000', message='Authorization unexpectedly allowed: '||statement;
end $$;
do $$
declare owner_id uuid:=gen_random_uuid(); admin_id uuid:=gen_random_uuid(); peer_id uuid:=gen_random_uuid(); outside_id uuid:=gen_random_uuid(); cid uuid; dm uuid; poll_id uuid; msg uuid; option_a uuid; option_b uuid; content jsonb:='{"kind":"movie","id":550,"title":"QA movie","image":"https://image.tmdb.org/t/p/w500/test.jpg"}';
begin
 insert into auth.users(id,email) select uid,uid||'@example.invalid' from unnest(array[owner_id,admin_id,peer_id,outside_id]) uid;
 insert into public.profiles(id,username,display_name) select uid,'qa_'||replace(uid::text,'-',''),'QA person' from unnest(array[owner_id,admin_id,peer_id,outside_id]) uid;
 insert into public.friend_requests(requester_id,target_id,status) values(owner_id,admin_id,'accepted'),(owner_id,peer_id,'accepted'),(admin_id,outside_id,'accepted');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true); execute 'set local role authenticated';
 cid:=public.kaidra_create_group('QA group controls',array[admin_id,peer_id]); dm:=public.get_or_create_conversation(admin_id);
 perform pg_temp.assert_ok((select role='owner' from public.conversation_participants where conversation_id=cid and user_id=owner_id),'Creator must be owner');
 perform public.kaidra_library_save(content,'favorites',true); perform public.kaidra_library_save(content,'watchlist',true); perform public.kaidra_library_save(content,'favorites',false);
 perform pg_temp.assert_ok((select is_watchlisted and not is_favorite from public.user_watchlist where user_id=owner_id and external_id='550'),'Favorites and watchlist must stay independent');
 perform public.kaidra_group_action(cid,'promote',admin_id);
 perform public.kaidra_group_action(cid,'permissions',null,'{"send_messages":"admins","create_polls":"admins"}');
 perform pg_temp.denied(format('select public.kaidra_leave_group(%L)',cid));
 perform pg_temp.denied(format('update public.conversation_participants set role=''owner'' where conversation_id=%L and user_id=%L',cid,peer_id));
 perform pg_temp.denied(format('insert into public.messages(conversation_id,sender_id,content,message_type) values(%L,%L,''fake event'',''system'')',cid,owner_id));
 perform pg_temp.denied(format('insert into public.messages(conversation_id,sender_id,content,message_type) values(%L,%L,''fake poll'',''poll'')',cid,owner_id));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',peer_id,'role','authenticated')::text,true);
 perform pg_temp.denied(format('insert into public.messages(conversation_id,sender_id,content) values(%L,%L,''denied'')',cid,peer_id));
 perform pg_temp.denied(format('select public.kaidra_create_poll(%L,''Denied'',array[''A'',''B''])',cid));
 perform pg_temp.denied(format('select public.kaidra_group_action(%L,''info'',null,''{"title":"No"}'')',cid));
 perform pg_temp.assert_ok(not exists(select 1 from public.user_watchlist where user_id=owner_id),'Private library leaked');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
 perform public.kaidra_group_action(cid,'info',null,'{"title":"Updated by admin","description":"QA"}');
 perform pg_temp.denied(format('select public.kaidra_group_action(%L,''demote'',%L)',cid,owner_id));
 perform pg_temp.denied(format('select public.kaidra_group_action(%L,''promote'',%L)',cid,peer_id));
 perform pg_temp.denied(format('select public.kaidra_group_action(%L,''remove'',%L)',cid,owner_id));
 perform pg_temp.denied(format('select public.kaidra_group_action(%L,''delete'')',cid));
 perform pg_temp.denied(format('select public.kaidra_group_action(%L,''permissions'',null,''{"send_messages":"everyone"}'')',cid));
 perform public.kaidra_add_group_members(cid,array[outside_id]);
 insert into public.messages(conversation_id,sender_id,content,mention_ids,shared_content) values(cid,admin_id,'@qa_person watch this',array[peer_id],content) returning id into msg;
 perform public.kaidra_pin(msg,true);
 poll_id:=public.kaidra_create_poll(cid,'Tonight?',array['Movie','Series'],false);
 select (options->0->>'id')::uuid,(options->1->>'id')::uuid into option_a,option_b from public.chat_polls where message_id=poll_id;
 perform public.kaidra_vote(poll_id,array[option_a]); perform public.kaidra_vote(poll_id,array[option_b]);
 perform pg_temp.assert_ok((select choice_ids=array[option_b] from public.poll_votes where message_id=poll_id and user_id=admin_id),'Changing a vote failed');
 perform pg_temp.denied(format('select public.kaidra_vote(%L,array[%L::uuid,%L::uuid])',poll_id,option_a,option_b));
 perform pg_temp.denied(format('select public.kaidra_vote(%L,array[%L::uuid])',poll_id,gen_random_uuid()));
 perform pg_temp.assert_ok((select count(*)=1 from public.kaidra_shared_history(cid)),'Shared history missing rich message');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',peer_id,'role','authenticated')::text,true);
 perform public.kaidra_vote(poll_id,array[option_a]);
 perform pg_temp.assert_ok(exists(select 1 from public.message_mentions where message_id=msg and user_id=peer_id),'Persisted mention missing');
 perform pg_temp.assert_ok((select (row->>'mentionCount')::int=1 from jsonb_array_elements(public.kaidra_inbox()) row where row->>'conversationId'=cid::text),'Unread mention emphasis missing');
 perform pg_temp.denied(format('select public.kaidra_pin(%L,false)',msg));
 perform public.kaidra_mark_read(cid);
 perform pg_temp.assert_ok((select (row->>'mentionCount')::int=0 from jsonb_array_elements(public.kaidra_inbox()) row where row->>'conversationId'=cid::text),'Mention unread did not clear');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
 perform public.kaidra_group_action(cid,'remove',outside_id);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outside_id,'role','authenticated')::text,true);
 perform pg_temp.assert_ok(not exists(select 1 from public.messages where conversation_id=cid),'Removed member retained messages');
 perform pg_temp.assert_ok(not exists(select 1 from public.chat_polls where conversation_id=cid),'Removed member retained polls');
 perform pg_temp.assert_ok(not exists(select 1 from public.poll_votes where conversation_id=cid),'Removed member retained votes');
 perform pg_temp.assert_ok(not exists(select 1 from public.message_pins where conversation_id=cid),'Removed member retained pins');
 perform pg_temp.assert_ok(exists(select 1 from public.chat_signals where user_id=outside_id and conversation_id=cid and reason='access_changed'),'Access revocation signal missing');
 perform pg_temp.denied(format('select public.kaidra_vote(%L,array[%L::uuid])',poll_id,option_a));
 perform pg_temp.denied(format('select public.kaidra_shared_history(%L)',cid));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 perform public.kaidra_group_action(cid,'transfer',peer_id); perform public.kaidra_leave_group(cid);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',peer_id,'role','authenticated')::text,true);
 perform pg_temp.assert_ok((select role='owner' from public.conversation_participants where conversation_id=cid and user_id=peer_id),'Ownership transfer failed');
 perform public.kaidra_group_action(cid,'delete');
 execute 'reset role';
 perform pg_temp.assert_ok(not exists(select 1 from public.conversations where id=cid),'Group delete failed');
end $$;
rollback;
