begin;
create function pg_temp.check_ok(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',label;end if;end $$;
create function pg_temp.refuse(statement text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or raise_exception or check_violation then return;end;raise exception using errcode='XX000',message='Unexpected permission: '||statement;end $$;
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();d uuid:=gen_random_uuid();cid uuid;cid2 uuid;token text;replacement text;res jsonb;path text;mid uuid;begin
 insert into auth.users(id,email) select u,u||'@example.invalid' from unnest(array[a,b,c,d]) u;
 insert into public.profiles(id,username,display_name,onboarding_completed) select u,'qa_'||left(replace(u::text,'-',''),16),'QA messenger member',true from unnest(array[a,b,c,d]) u;
 insert into public.friend_requests(requester_id,target_id,status) values(a,b,'accepted');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';cid:=public.kaidra_create_group('Messenger QA',array[b]);token:=public.kaidra_group_link_manage(cid,'create')->>'token';
 perform pg_temp.refuse('select * from public.group_invite_links');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',c,'role','authenticated')::text,true);
 res:=public.kaidra_group_join(token);perform pg_temp.check_ok(res->>'status'='preview' and not(res?'members'),'Preview exposed roster or failed');
 perform pg_temp.refuse(format('select public.kaidra_group_link_manage(%L,''create'')',cid));
 perform pg_temp.refuse(format('select public.kaidra_group_requests(%L)',cid));
 res:=public.kaidra_group_join(token,true);perform pg_temp.check_ok(res->>'status'='joined','Join failed');res:=public.kaidra_group_join(token,true);perform pg_temp.check_ok(res->>'status'='member','Join not idempotent');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);perform public.kaidra_group_link_manage(cid,'approval',true);replacement:=public.kaidra_group_link_manage(cid,'create')->>'token';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',d,'role','authenticated')::text,true);perform pg_temp.refuse(format('select public.kaidra_group_join(%L,true)',token));res:=public.kaidra_group_join(replacement,true);perform pg_temp.check_ok(res->>'status'='pending','Approval bypassed');perform pg_temp.check_ok(not public.kaidra_is_conversation_member(cid),'Pending request grants access');perform pg_temp.refuse(format('select public.kaidra_group_requests(%L,%L,''approve'')',cid,d));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);res:=public.kaidra_group_requests(cid);perform pg_temp.check_ok(jsonb_array_length(res)=1,'Admin request list failed');perform public.kaidra_group_requests(cid,d,'approve');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',d,'role','authenticated')::text,true);perform pg_temp.check_ok(public.kaidra_is_conversation_member(cid),'Approval did not grant membership');
 execute 'reset role';path:=cid||'/'||gen_random_uuid()||'.webp';insert into storage.objects(bucket_id,name,metadata) values('chat-media',path,'{"mimetype":"image/webp","size":1024}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';
 insert into public.messages(conversation_id,sender_id,content,message_type,media_url,media_metadata) values(cid,a,'','sticker',path,'{"name":"Shared sticker","size":99,"mime":"fake"}') returning id into mid;
 perform pg_temp.check_ok((select media_metadata->>'size'='1024' and media_metadata->>'mime'='image/webp' from public.messages where id=mid),'Client supplied trusted metadata');
 perform pg_temp.refuse(format('insert into public.messages(conversation_id,sender_id,content,message_type,media_url) values(%L,%L,'''',''video'',%L)',cid,a,path));
 perform pg_temp.refuse(format('insert into public.messages(conversation_id,sender_id,content,message_type,media_url) values(%L,%L,'''',''sticker'',%L)',cid,a,cid||'/'||gen_random_uuid()||'.webp'));
 cid2:=public.kaidra_create_group('Another room',array[b]);perform pg_temp.refuse(format('insert into public.messages(conversation_id,sender_id,content,message_type,media_url) values(%L,%L,'''',''sticker'',%L)',cid2,a,path));
 perform pg_temp.check_ok(exists(select 1 from public.kaidra_shared_history(cid,'media') where id=mid),'Sticker missing in shared history');
 execute 'reset role';update public.group_invite_links set expires_at=now()-interval '1 minute' where conversation_id=cid;execute 'set local role authenticated';perform pg_temp.refuse(format('select public.kaidra_group_join(%L)',replacement));
 execute 'reset role';update public.group_invite_links set expires_at=now()+interval '1 day' where conversation_id=cid;insert into public.user_blocks(user_id,blocked_user) values(a,b);perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);execute 'set local role authenticated';perform pg_temp.refuse(format('select public.kaidra_group_join(%L)',replacement));execute 'reset role';delete from public.user_blocks where user_id=a and blocked_user=b;perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';
 perform public.kaidra_group_link_manage(cid,'revoke');perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);perform pg_temp.refuse(format('select public.kaidra_group_join(%L)',replacement));
 perform pg_temp.refuse(format('insert into public.user_stickers(user_id,label,path) values(%L,''Other library'',%L)',a,a||'/'||gen_random_uuid()||'.webp'));
 execute 'reset role';
end $$;
rollback;
