import http from 'node:http';
import { readFile, writeFile, mkdir, mkdtemp } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
const root=resolve(import.meta.dirname,'..');
const server=http.createServer(async(req,res)=>{
  const path=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);
  if(!path.startsWith(root+'/')){res.writeHead(403);return res.end();}
  try{
    let body=await readFile(path);
    if(path.endsWith('/js/supabase-client.js'))body=Buffer.from(body.toString().replace('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm','/tests/mock-supabase.js'));
    res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'})[extname(path)]||'text/plain');res.end(body);
  }catch{res.writeHead(404);res.end('Not found');}
});
await new Promise((done,reject)=>{server.once('error',reject);server.listen(8765,'127.0.0.1',done);});
let browserProcess;
const browserDir = await mkdtemp('/tmp/kaidra-test-browser-');
try { await fetch('http://127.0.0.1:9222/json'); }
catch {
  browserProcess = spawn('google-chrome',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--remote-debugging-port=9222',`--user-data-dir=${browserDir}`,'about:blank'],{stdio:'ignore'});
  const start=Date.now(); while(true) { try { await fetch('http://127.0.0.1:9222/json'); break; } catch { if(Date.now()-start>10000) throw new Error('Chrome did not start'); await new Promise(resolve=>setTimeout(resolve,100)); } }
}
const tabs=await(await fetch('http://127.0.0.1:9222/json')).json();
const tab=tabs.find(tab=>tab.type==='page');
const ws=new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((done,reject)=>{ws.onopen=done;ws.onerror=reject;});
let fileChooser=null;let seq=0;const pending=new Map(),errors=[];
ws.onmessage=({data})=>{const value=JSON.parse(data);if(value.id){const item=pending.get(value.id);pending.delete(value.id);if(value.error)item.reject(value.error);else item.resolve(value.result);}else if(value.method==='Page.fileChooserOpened')fileChooser=value.params;else if(value.method==='Runtime.exceptionThrown')errors.push(value.params.exceptionDetails.exception?.description||value.params.exceptionDetails.text);};
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Browser command timed out: '+method));},20000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
async function perform(expression){return evaluate(`(async()=>{${expression}})()`);}
async function wait(expression){const start=Date.now();while(Date.now()-start<10000){if(await evaluate(`(()=>{try{return Boolean(${expression})}catch{return false}})()`))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timed out: '+expression);}
const clickText=(selector,text)=>evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(node=>node.textContent.trim()===${JSON.stringify(text)}).click()`);
const click=(selector)=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);

async function screenshot(name) { await new Promise(resolve=>setTimeout(resolve,350)); await evaluate('document.querySelector("#app-status")?.classList.add("hidden")'); await mkdir('/tmp/kaidra-qa',{recursive:true}); await writeFile('/tmp/kaidra-qa/'+name+'.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64')); }
async function size(width,height=900) { await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<700}); }
async function route(tab) { await evaluate("document.dispatchEvent(new CustomEvent('kaidra:navigate',{detail:{tab:"+JSON.stringify(tab)+"}}))"); await new Promise(r=>setTimeout(r,80)); }
async function send(text) { await evaluate("document.querySelector('#message-text-input').value="+JSON.stringify(text)+";document.querySelector('#message-text-input').dispatchEvent(new Event('input'));document.querySelector('#message-form').requestSubmit()"); await wait('!document.querySelector(".is-sending")'); }
async function chooseFile(action,path){fileChooser=null;await call('Page.setInterceptFileChooserDialog',{enabled:true});await action();const start=Date.now();while(!fileChooser){if(Date.now()-start>5000)throw new Error('File chooser did not open');await new Promise(r=>setTimeout(r,50));}await call('DOM.setFileInputFiles',{files:[path],backendNodeId:fileChooser.backendNodeId});await call('Page.setInterceptFileChooserDialog',{enabled:false});}
let windowInvite;
try {
 await call('Runtime.enable');await call('Page.enable');await call('Network.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});await call('Storage.clearDataForOrigin',{origin:'http://127.0.0.1:8765',storageTypes:'all'});await size(390,844);
 await call('Page.navigate',{url:'http://127.0.0.1:8765/app.html#inbox'});await wait('window.__mock && document.querySelector(".conversation-row")');await click('.conversation-row');await wait('document.querySelector("#chat-connection-status").textContent==="Connected"');
 for(const id of ['voice-record-btn','composer-attachment','composer-camera','composer-stickers'])assert(await evaluate(`document.getElementById('${id}').getBoundingClientRect().width>=40&&!document.getElementById('${id}').disabled`));
 await click('#voice-record-btn');await wait('document.querySelector("#voice-recorder").dataset.phase==="recording"');await new Promise(r=>setTimeout(r,1200));await click('#voice-stop-btn');await wait('document.querySelector("#voice-recorder").dataset.phase==="preview"');await click('#voice-send-btn');await wait('document.querySelector(".voice-message") && !document.querySelector(".is-sending")');await click('.voice-message button[aria-label="Play voice note"]');await wait('document.querySelector(".voice-message audio").readyState>=1 && !document.querySelector(".voice-seek").disabled');await wait('document.querySelector(".voice-message audio").currentTime>0');await click('.voice-speed');assert.equal(await evaluate('document.querySelector(".voice-message audio").playbackRate'),1.5);await screenshot('messenger-voice-mobile');
 await click('#composer-camera');assert(await evaluate('/Gallery|Take photo|Record video/.test(document.querySelector(".context-menu").textContent)'));await click('.context-layer .modal-heading button');await click('#composer-attachment');assert(await evaluate('/Document/.test(document.querySelector(".context-menu").textContent)'));await click('.context-layer .modal-heading button');
 await perform(`window.__mock.mediaFile=await new Promise(resolve=>{const c=document.createElement('canvas');c.width=c.height=100;const ctx=c.getContext('2d');ctx.fillStyle='#b69aff';ctx.fillRect(10,10,80,80);c.toBlob(blob=>resolve(new File([blob],'my-sticker.png',{type:'image/png'})));});const {uploadMedia}=await import('/js/chat-media.js');window.__mock.stickerId=crypto.randomUUID();const media=await uploadMedia(window.__mock.a,window.__mock.mediaFile,window.__mock.stickerId,'sticker');const {sendMessage}=await import('/js/supabase-client.js');await sendMessage({id:window.__mock.stickerId,conversationId:window.__mock.a,senderId:window.__mock.me,content:'',messageType:media.message_type,mediaUrl:media.media_url,mediaMetadata:media.media_metadata});`);
 await wait('document.querySelector(".chat-sticker") && document.querySelector(".media-forward")');await click('.media-forward');await wait('document.querySelector("#new-chat-list .person-row")');await evaluate('[...document.querySelectorAll("#new-chat-list .person-row")].find(row=>row.textContent.includes("Bob")).click()');await wait('window.__mock.copies?.length===1');assert.equal(await evaluate('window.__mock.copies[0].bucket'),'chat-media');assert(await evaluate('window.__mock.db.messages.some(m=>m.conversation_id===window.__mock.b&&m.message_type==="sticker"&&m.media_metadata.name==="my-sticker.png")'));
 await writeFile('/tmp/kaidra-import-sticker.png',Buffer.from(await perform('return [...new Uint8Array(await window.__mock.mediaFile.arrayBuffer())]')));await click('#composer-stickers');await wait('document.querySelector(".sticker-picker")');await chooseFile(()=>clickText('.sticker-picker button','Import stickers'),'/tmp/kaidra-import-sticker.png');await wait('window.__mock.db.user_stickers.length===1 && document.querySelector(".sticker-send img").src.startsWith("blob:")');await click('.sticker-send');await wait('!document.querySelector(".sticker-picker") && window.__mock.db.messages.filter(m=>m.message_type==="sticker").length===3');
 await writeFile('/tmp/kaidra-message.pdf',Buffer.from('%PDF-1.4\n1 0 obj<< /Type /Catalog >>endobj\n%%EOF'));await click('#composer-attachment');await chooseFile(()=>clickText('.context-action','Document'),'/tmp/kaidra-message.pdf');await wait('document.querySelector(".chat-document") && !document.querySelector(".is-sending")');assert(await evaluate('document.querySelector(".chat-document").textContent.includes("kaidra-message.pdf")'));
 await click('#composer-camera');await chooseFile(()=>clickText('.context-action','Gallery · photos and videos'),'/tmp/kaidra-import-sticker.png');await wait('document.querySelector("img.chat-media") && window.__mock.db.messages.some(m=>m.message_type==="image")');
 const videoBytes=await perform(`return await new Promise(resolve=>{const c=document.createElement('canvas');c.width=160;c.height=90;const stream=c.captureStream(10),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),parts=[];rec.ondataavailable=e=>parts.push(e.data);rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());resolve([...new Uint8Array(await new Blob(parts,{type:'video/webm'}).arrayBuffer())]);};rec.start();let frames=0;const timer=setInterval(()=>{const ctx=c.getContext('2d');ctx.fillStyle=frames++%2?'#a388e0':'#253038';ctx.fillRect(0,0,160,90);if(frames===8){clearInterval(timer);rec.stop();}},100);});`);await writeFile('/tmp/kaidra-message.webm',Buffer.from(videoBytes));await click('#composer-camera');await chooseFile(()=>clickText('.context-action','Gallery · photos and videos'),'/tmp/kaidra-message.webm');await wait('document.querySelector("video.chat-media")?.readyState>=1');assert(await evaluate('document.querySelector("[data-message-type=video] .media-forward")!==null'));
 await perform(`const {supabase}=await import('/js/supabase-client.js');window.__mock.group=await (await import('/js/supabase-client.js')).chatAction('kaidra_create_group',{group_title:'Kaidra crew',member_ids:[window.__mock.alice,window.__mock.bob]});window.__mock.emit('chat_signals','UPDATE',{user_id:window.__mock.me,conversation_id:window.__mock.group});`);await route('inbox/'+await evaluate('window.__mock.group'));await wait('document.querySelector("#dm-active-name").textContent==="Kaidra crew"');await click('#chat-info-btn');await wait('document.querySelector("#chat-members .group-member-list .person-row")');assert(await evaluate('document.querySelector("#chat-info-modal .social-modal-card").getBoundingClientRect().height>=innerHeight-2'));await screenshot('messenger-group-info-mobile');
 await evaluate('const search=document.querySelector(".group-members-heading input");search.value="Bob";search.dispatchEvent(new Event("input"))');assert.equal(await evaluate('document.querySelectorAll(".group-member-list .person-row:not(.hidden)").length'),1);
 await clickText('.group-info-actions button','Permissions');await wait('document.querySelector(".group-permissions-panel .primary-button")?.disabled===false');await click('.group-permissions-panel input[aria-label="Approve new members"]');await clickText('.group-permissions-panel button','Save permissions');await wait('!document.querySelector(".group-permissions-panel")');assert(await evaluate('window.__mock.db.conversations.find(c=>c.id===window.__mock.group).join_approval'));
 await clickText('.group-quick-actions button','Invite link');await wait('document.querySelector(".group-invite-panel")');await clickText('.group-invite-panel button','Create invite link');await wait('document.querySelector(".group-invite-panel input")');windowInvite=await evaluate('document.querySelector(".group-invite-panel input").value');assert(/#join\/[0-9a-f]{64}$/.test(windowInvite));await screenshot('messenger-group-invite-mobile');await click('.group-invite-panel .modal-heading button');await click('#chat-info-modal .modal-heading button');
 await route(windowInvite.split('#')[1]);await wait('document.querySelector(".group-join-panel")');await clickText('.group-join-panel button','Open group');await wait('!document.querySelector(".group-join-panel")');
 for(const width of [320,390,768,1366]){await size(width);assert(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'));await click('#chat-info-btn');await wait('document.querySelector(".group-info-identity")');assert(await evaluate('document.querySelector("#chat-info-modal .social-modal-card").scrollWidth<=document.querySelector("#chat-info-modal .social-modal-card").clientWidth+1'));if(width===1366)await screenshot('messenger-group-info-desktop');await click('#chat-info-modal .modal-heading button');}
 assert.deepEqual(errors,[]);console.log('PASS messenger browser: direct controls, recorded voice/play/seek/speed, real sticker upload and private forwarding/library, camera/gallery/document menus, group full view/member search/permissions/invite route, mobile/tablet/desktop bounds.');
} catch(error){console.error(error);console.error('Runtime errors:',errors);process.exitCode=1;await screenshot('messenger-failure').catch(()=>{});}
finally{ws.close();server.close();browserProcess?.kill();}
