// Browser-only QA adapter, wired by combat-browser.mjs. Never imported in production.
import { kits,resolveCombat } from '/tests/combat-engine.js';
export function install(control){const {db,me,alice,bob,a,emit}=control,identity=id=>db.battle_identities.find(i=>i.user_id===id),uids=[me,alice,bob,'00000000-0000-4000-8000-000000000006'];
 Object.assign(db,{rpg_parties:[],rpg_party_members:[],rpg_party_invites:[],battle_rivalries:[]});
 control.setupCombat=async(classes=['warrior','wizard'],phase='playing')=>{const id=crypto.randomUUID();db.battles.filter(b=>b.combat_version===1&&['pending','active'].includes(b.status)).forEach(b=>b.status='cancelled');control.combatEvents=[];const battle={id,conversation_id:a,challenger_id:me,challenged_id:classes.length>2?bob:alice,type:'direct',combat_version:1,status:phase==='waiting'?'pending':'active',context:classes.length>2?{party_battle:true,party_a_name:'Nightfall',party_b_name:'Daybreak'}:{},created_at:new Date().toISOString()};db.battles.push(battle);for(let i=0;i<classes.length;i++){const uid=uids[i];if(!db.profiles.some(p=>p.id===uid))db.profiles.push({id:uid,username:'member'+i,display_name:'Member '+i});const old=identity(uid);if(old)old.class_id=classes[i];else db.battle_identities.push({user_id:uid,class_id:classes[i],acknowledged:true});}control.combat={id,battle,phase,active_id:me,turn:1,round:1,revision:1,deadline:new Date(Date.now()+25000).toISOString(),seed:'test-only-server-seed',winning_team:null,fighters:classes.map((class_id,i)=>({user_id:uids[i],team:i<classes.length/2?1:2,class_id,hp:kits[class_id].hp,max_hp:kits[class_id].hp,resource:kits[class_id].start,turn_order:i+1,turns:0,timeouts:0,ready:i===0})),effects:[],cooldowns:[]};return id;};
 control.combatState=()=>{const s=control.combat,{seed,battle,...combat}=s;return {battle,combat,server_now:new Date().toISOString(),fighters:s.fighters.map(f=>({...f,name:db.profiles.find(p=>p.id===f.user_id)?.display_name,identity:identity(f.user_id)})),effects:s.effects,cooldowns:s.cooldowns,events:control.combatEvents,predictions:[],own_rewards:battle.status==='resolved'?[{xp:25}]:[],own_stats:{xp:25,wins:1,battles:1,streak:1,best_streak:1},abilities:kits[s.fighters.find(f=>f.user_id===me).class_id].abilities};};
 control.combatAct=intent=>{const s=control.combat,battle=s.battle,result=resolveCombat(s,{actor:intent.actor||me,action:intent.action||'act',ability:intent.ability_id,target:intent.target_id,request_id:intent.request_id||crypto.randomUUID(),expected_revision:intent.expected_revision??s.revision});control.combat={...result.state,battle};if(result.state.phase==='finished'){battle.status='resolved';battle.winner_id=result.state.winning_team===1?me:battle.challenged_id;}control.combatEvents.push({sequence:result.state.revision,request_id:intent.request_id,payload:{events:result.events}});emit('battle_events','INSERT',{battle_id:s.id});return control.combatState();};
 control.partyRPC=(name,args)=>{if(name==='kaidra_combat_state')return control.combatState();if(name==='kaidra_combat_history')return db.battles.filter(b=>b.combat_version===1).map(b=>({...b,fighters:control.combat.fighters.map(f=>({...f,id:f.user_id,name:db.profiles.find(p=>p.id===f.user_id)?.display_name})),own_reward:b.status==='resolved'?25:null}));if(name==='kaidra_party_create'){const id=args.request_id;db.rpg_parties.push({id,name:args.party_name,emblem:args.emblem,leader_id:me,conversation_id:a});db.rpg_party_members.push({party_id:id,user_id:me});return id;}if(name==='kaidra_party_state'){const party=db.rpg_parties.find(p=>p.id===args.target_party);return {party,members:db.rpg_party_members.filter(m=>m.party_id===party.id).map(m=>({...m,id:m.user_id,name:db.profiles.find(p=>p.id===m.user_id).display_name,leader:party.leader_id===m.user_id,identity:identity(m.user_id)})),own_invite:null};}if(name==='kaidra_party_invite'){db.rpg_party_invites.push({party_id:args.target_party,user_id:args.target_user,status:'pending',created_at:new Date().toISOString()});return true;}if(name==='kaidra_party_opponents')return [];};
}
