begin;
create function pg_temp.check_ok(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception '%',label;end if;end $$;
create function pg_temp.refuse(statement text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or raise_exception or check_violation then return;end;raise exception using errcode='XX000',message='Unexpected permission: '||statement;end $$;
do $$declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();d uuid:=gen_random_uuid();ref jsonb:=jsonb_build_object('sport','football','provider','api-sports','entity_type','team','external_id','999997001');other_ref jsonb:=jsonb_build_object('sport','football','provider','api-sports','entity_type','team','external_id','999997002');event_ref jsonb:=jsonb_build_object('sport','football','provider','api-sports','entity_type','event','external_id','999997003');cid uuid;m uuid;bid uuid;s jsonb;key text:='qa:'||gen_random_uuid()::text;begin
 insert into auth.users(id,email,created_at) select id,id||'@example.invalid',now()-interval '30 days' from unnest(array[a,b,c,d]) id;
 insert into public.profiles(id,username,display_name) select id,'qa_'||left(replace(id::text,'-',''),16),'QA sports member' from unnest(array[a,b,c,d]) id;
 insert into public.battle_identities(user_id,class_id,determination_version) values(a,'warrior',1),(b,'wizard',1);
 insert into public.friend_requests(requester_id,target_id,status) values(a,b,'accepted'),(a,d,'accepted');
 insert into public.sports_entities values('football','api-sports','team','999997001','QA Team A','{"team":{"id":999997001,"name":"QA Team A"}}',now()),('football','api-sports','team','999997002','QA Team B','{"team":{"id":999997002,"name":"QA Team B"}}',now());
 insert into public.sports_entities values('football','api-sports','event','999997003','QA Match',jsonb_build_object('fixture',jsonb_build_object('id',999997003,'status',jsonb_build_object('short','NS'),'date',now()+interval '30 minutes'),'teams',jsonb_build_object('home',jsonb_build_object('id',999997001),'away',jsonb_build_object('id',999997002))),now());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';
 perform public.kaidra_sports_follow(ref,'support');perform pg_temp.check_ok((select is_primary and not is_public from public.sports_follows where user_id=a),'Primary default privacy failed');
 perform pg_temp.refuse(format('insert into public.sports_follows(user_id,sport,provider,entity_type,external_id) values(%L,''football'',''api-sports'',''team'',''999997002'')',b));
 perform pg_temp.refuse('select public.kaidra_sports_cache_claim(''evil'')');perform pg_temp.refuse('select public.kaidra_sports_ingest(''[]'')');perform pg_temp.refuse('select public.kaidra_sports_deliver(''999997003'',''results'',''evil'',''evil'')');
 perform pg_temp.refuse(format('select public.kaidra_sports_follow(%L::jsonb,''support'')',other_ref));
 perform public.kaidra_sports_follow(other_ref,'follow');perform pg_temp.check_ok((select count(*)=2 from public.sports_follows where user_id=a),'Multiple follows failed');
 perform public.kaidra_sports_follow(other_ref,'support',false,'999997001');perform pg_temp.check_ok((select count(*)=1 from public.sports_follows where user_id=a and is_primary),'Primary uniqueness failed');
 perform public.kaidra_sports_follow(ref,'support',false,'999997002');
 perform public.kaidra_sports_side(event_ref,'home');perform pg_temp.check_ok(public.kaidra_sports_match_social(event_ref)#>>'{own,side}'='home','Match choice failed');perform public.kaidra_sports_side(event_ref,'away');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform pg_temp.check_ok(not exists(select 1 from public.sports_follows where user_id=a),'Raw private follows leaked');perform pg_temp.check_ok(public.kaidra_sports_profile(a)='[]'::jsonb,'Private support leaked');perform public.kaidra_sports_follow(ref,'support',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',c,'role','authenticated')::text,true);perform public.kaidra_sports_follow(ref,'support',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',d,'role','authenticated')::text,true);perform public.kaidra_sports_follow(ref,'support',false);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 s:=public.kaidra_sports_friends(ref);perform pg_temp.check_ok(jsonb_array_length(s)=1 and s->0->>'id'=b::text,'Private friend or unrelated supporter leaked');
 cid:=public.get_or_create_conversation(b);
 insert into public.messages(conversation_id,sender_id,content,message_type,sports_context) values(cid,a,'Team A will win','discussion',ref||jsonb_build_object('title','Forged title')) returning id into m;
 perform pg_temp.check_ok((select sports_context->>'title'='QA Team A' from public.messages where id=m),'Untrusted Discussion metadata accepted');
 perform pg_temp.refuse(format('insert into public.messages(conversation_id,sender_id,content,message_type,sports_context) values(%L,%L,''Fake'',''discussion'',''{"sport":"football","provider":"api-sports","entity_type":"team","external_id":"9999999999"}'')',cid,a));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);perform public.kaidra_discussion_position(m,'disagree');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);bid:=public.kaidra_battle_create(cid,b,'','',jsonb_build_object('entry_type','discussion','discussion_message_id',m));perform pg_temp.check_ok((select context#>>'{sports,external_id}'='999997001' from public.battles where id=bid),'Sports battle context lost');perform pg_temp.refuse(format('select public.kaidra_battle_action(%L,''accept'')',bid));
 perform pg_temp.refuse(format('select public.kaidra_battle_create(%L,%L,'''','''',''{"entry_type":"direct"}'')',cid,a));perform pg_temp.refuse(format('select public.kaidra_battle_create(%L,%L,'''','''',''{"entry_type":"direct"}'')',cid,c));
 perform public.kaidra_sports_preferences(true,true,true,true);
 execute 'reset role';perform pg_temp.check_ok(public.kaidra_sports_deliver('999997003','reminders','QA Reminder','QA')=1,'Enabled reminder delivery failed');perform pg_temp.check_ok(public.kaidra_sports_deliver('999997003','reminders','QA Reminder','QA')=0,'Notification deduplication failed');
 perform pg_temp.check_ok(public.kaidra_sports_deliver('999997003','lineups','QA Lineup','QA')=0,'Unofficial lineup delivered');
 insert into public.sports_provider_cache(cache_key,data,expires_at) values('football:lineups:999997003','{"response":[{"team":{"id":999997001},"startXI":[{"player":{"id":999997004}}]}]}',now()+interval '1 hour');
 perform pg_temp.check_ok(public.kaidra_sports_deliver('999997003','lineups','QA Lineup','QA')=1,'Official lineup delivery failed');
 update public.sports_notification_preferences set results=false where user_id=a;
 update public.sports_entities set snapshot=jsonb_set(snapshot,'{fixture,status,short}','"FT"') where entity_type='event' and external_id='999997003';
 perform pg_temp.check_ok(public.kaidra_sports_deliver('999997003','results','QA Result','QA')=0,'Disabled result category delivered');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);execute 'set local role authenticated';perform pg_temp.refuse(format('select public.kaidra_sports_side(%L::jsonb,''home'')',event_ref));perform pg_temp.check_ok(public.kaidra_sports_match_social(event_ref)#>>'{own,side}'='away','Final-match support changed');
 execute 'reset role';update public.sports_notification_preferences set results=true where user_id=a;insert into public.social_preferences(user_id,notifications) values(a,'{"football":false}') on conflict(user_id) do update set notifications=excluded.notifications;
 perform pg_temp.check_ok(public.kaidra_sports_deliver('999997003','results','QA Result','QA')=0,'Global notification opt-out ignored');
 s:=public.kaidra_sports_cache_claim(key);perform pg_temp.check_ok(s->>'state'='fetch','Lease acquisition failed');s:=public.kaidra_sports_cache_claim(key);perform pg_temp.check_ok(s->>'state'='busy','Duplicate cache request got another lease');perform public.kaidra_sports_cache_store(key,'{"response":[]}',600);s:=public.kaidra_sports_cache_claim(key);perform pg_temp.check_ok(s->>'state'='hit','Shared cache hit failed');
 update public.sports_provider_budget set requests=80 where day=(now() at time zone 'UTC')::date;s:=public.kaidra_sports_cache_claim(key||':quota');perform pg_temp.check_ok(s->>'state'='quota','Shared quota enforcement failed');
 perform public.kaidra_sports_cache_store(key,null,600,'PROVIDER_QUOTA_LIMIT',2);perform pg_temp.check_ok((select blocked_until>now() from public.sports_provider_budget where day=(now() at time zone 'UTC')::date),'Provider quota block failed');
end $$;
rollback;
select 'PASS Sports RLS/privacy/confirmed primary changes/trusted context/match locking/notifications/deduplication/global and category opt-out/cache lease/budget and challenge membership protections' result;
