begin;
alter table public.battle_classes drop constraint battle_classes_id_check;
alter table public.battle_classes add constraint battle_classes_id_check check(id in('warrior','wizard','ninja','guardian','rogue','healer','ranger','berserker'));
insert into public.battle_classes(id,display_name,attack_style,defensive_style,visual_identity) values('healer','Healer','Restoration and decisive light','Purification, shielding and regeneration','restoration'),('ranger','Ranger','Precision, marking and ranged pressure','Distance and traps','projectile'),('berserker','Berserker','Aggression and measured danger','Rage and retaliatory pressure','rage');
alter table public.battle_classes add column base_hp integer not null default 100,add column starting_resource integer not null default 100,add column initiative integer not null default 1,add column resource_name text not null default 'Energy';
alter table public.battles add column combat_version integer not null default 0;
alter table public.battles alter column combat_version set default 1;
alter table public.battles drop constraint battles_outcome_check;
alter table public.battles add constraint battles_outcome_check check(outcome in('community_vote','concession','draw','combat'));
create table public.battle_teams(battle_id uuid references public.battles(id) on delete cascade,side integer check(side in(1,2)),party_id uuid,primary key(battle_id,side));
create table public.battle_participants(battle_id uuid references public.battles(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,team integer not null, class_id text references public.battle_classes(id),hp integer not null default 100,max_hp integer not null default 100,resource integer not null default 100,turn_order integer not null default 0,turns integer not null default 0,timeouts integer not null default 0,ready boolean not null default false,primary key(battle_id,user_id),foreign key(battle_id,team) references public.battle_teams(battle_id,side),check(hp between 0 and max_hp and resource between 0 and 100 and max_hp between 1 and 200 and turns>=0 and timeouts>=0));
create unique index battle_one_turn_order on public.battle_participants(battle_id,turn_order) where turn_order>0;
create table public.battle_combat_state(battle_id uuid primary key references public.battles(id) on delete cascade,phase text not null default 'waiting' check(phase in('waiting','playing','finished')),active_id uuid,turn integer not null default 1,round integer not null default 1,revision integer not null default 0,deadline timestamptz,seed uuid not null default gen_random_uuid(),winning_team integer,check(turn>0 and round>0 and revision>=0),foreign key(battle_id,active_id) references public.battle_participants(battle_id,user_id));
create table public.battle_status_effects(battle_id uuid references public.battles(id) on delete cascade,id text,kind text not null,source uuid not null,target uuid not null,amount integer not null,expires integer not null,charges integer not null default -1,data jsonb,primary key(battle_id,id),foreign key(battle_id,source) references public.battle_participants(battle_id,user_id),foreign key(battle_id,target) references public.battle_participants(battle_id,user_id));
create table public.battle_cooldowns(battle_id uuid references public.battles(id) on delete cascade,user_id uuid,ability_id text,ready_turn integer not null,primary key(battle_id,user_id,ability_id),foreign key(battle_id,user_id) references public.battle_participants(battle_id,user_id));
create table public.battle_events(battle_id uuid references public.battles(id) on delete cascade,sequence integer not null,request_id uuid not null,actor uuid not null,ability_id text,target_id uuid,payload jsonb not null,created_at timestamptz not null default now(),primary key(battle_id,sequence),unique(battle_id,request_id),foreign key(battle_id,actor) references public.battle_participants(battle_id,user_id));
do $$declare t text;begin foreach t in array array['battle_teams','battle_participants','battle_combat_state','battle_status_effects','battle_cooldowns','battle_events'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant all on public.%I to service_role',t);execute format('create policy "Conversation combat" on public.%I for select to authenticated using(public.kaidra_battle_visible(battle_id))',t);if t<>'battle_combat_state' then execute format('grant select on public.%I to authenticated',t);end if;end loop;end $$;
grant select(battle_id,phase,active_id,turn,round,revision,deadline,winning_team) on public.battle_combat_state to authenticated;
create function public.kaidra_combat_prepare() returns trigger language plpgsql security definer set search_path='' as $$begin
 if new.combat_version=1 then
 insert into public.battle_teams values(new.id,1,null),(new.id,2,null);
 insert into public.battle_participants(battle_id,user_id,team,ready) values(new.id,new.challenger_id,1,true),(new.id,new.challenged_id,2,false);
 insert into public.battle_combat_state(battle_id) values(new.id);
 end if;return new;
end $$;
create trigger kaidra_combat_prepare after insert on public.battles for each row execute function public.kaidra_combat_prepare();
create function public.kaidra_combat_start(target_battle uuid) returns void language plpgsql security definer set search_path='' as $$declare s public.battle_combat_state;begin
 select * into s from public.battle_combat_state where battle_id=target_battle for update;if s.phase<>'waiting' then return;end if;
 if exists(select 1 from public.battle_participants p where battle_id=target_battle and (not ready or not exists(select 1 from public.battle_identities where user_id=p.user_id))) then return;end if;
 update public.battle_participants p set class_id=i.class_id,hp=c.base_hp,max_hp=c.base_hp,resource=c.starting_resource from public.battle_identities i join public.battle_classes c on c.id=i.class_id where p.battle_id=target_battle and p.user_id=i.user_id;
 with ranked as(select p.user_id,row_number() over(order by c.initiative desc,md5(s.seed::text||p.user_id::text)) n from public.battle_participants p join public.battle_classes c on c.id=p.class_id where p.battle_id=target_battle) update public.battle_participants p set turn_order=r.n from ranked r where p.battle_id=target_battle and p.user_id=r.user_id;
 update public.battle_combat_state set phase='playing',active_id=(select user_id from public.battle_participants where battle_id=target_battle and turn_order=1),deadline=now()+interval '25 seconds',revision=revision+1 where battle_id=target_battle;
 update public.battles set status='active',accepted_at=now(),ends_at=now()+interval '2 hours' where id=target_battle;
end $$;
-- New challenges preserve social validation and Discussion references in the existing function.
create or replace function public.kaidra_battle_create(target_conversation uuid,target_user uuid,topic text,stance text,context jsonb default '{}',request_id uuid default gen_random_uuid()) returns uuid language plpgsql security definer set search_path='' as $$begin
 if not exists(select 1 from public.battle_identities where user_id=auth.uid()) then raise exception 'Awaken your battle identity before challenging';end if;
 return public.kaidra_battle_create_internal(target_conversation,target_user,topic,stance,case when context='{}'::jsonb then '{"entry_type":"direct"}'::jsonb else context end,request_id);
end $$;
create or replace function public.kaidra_battle_action(target_battle uuid,action text,value text default '') returns void language plpgsql security definer set search_path='' as $$declare b public.battles;begin
 select * into b from public.battles where id=target_battle for update;if not public.kaidra_battle_visible(target_battle) then raise exception 'Conversation membership required';end if;
 if b.combat_version=0 then perform public.kaidra_battle_action_internal(target_battle,action,value);return;end if;
 if action='accept' then
 if b.status<>'pending' or b.created_at<now()-interval '1 day' or not exists(select 1 from public.battle_participants where battle_id=b.id and user_id=auth.uid() and not ready) or not exists(select 1 from public.battle_identities where user_id=auth.uid()) or not public.kaidra_pair_allowed(b.challenger_id,b.challenged_id) then raise exception 'Only an invited fighter can accept after awakening';end if;
 update public.battle_participants set ready=true where battle_id=b.id and user_id=auth.uid();perform public.kaidra_combat_start(b.id);
 elsif action in('decline','cancel') then
 if b.status<>'pending' or(action='cancel' and auth.uid()<>b.challenger_id) or(action='decline' and not exists(select 1 from public.battle_participants where battle_id=b.id and user_id=auth.uid() and not ready)) then raise exception 'Only the inviter can cancel or an invitee decline';end if;
 update public.battles set status=case when action='decline' then 'declined' else 'cancelled' end where id=b.id;update public.battle_combat_state set phase='finished',active_id=null,deadline=null,revision=revision+1 where battle_id=b.id;
 elsif action='predict' then
 if b.status<>'pending' or exists(select 1 from public.battle_participants where battle_id=b.id and user_id=auth.uid()) or not exists(select 1 from public.battle_participants where battle_id=b.id and user_id::text=value) then raise exception 'Only spectators can predict before combat begins';end if;
 insert into public.battle_votes values(b.id,auth.uid(),value::uuid,now()) on conflict(battle_id,user_id) do update set side=excluded.side,created_at=excluded.created_at;
 else raise exception 'Use the arena for combat. Spectators never decide the winner';end if;
end $$;
create function public.kaidra_combat_finish(target_battle uuid) returns void language plpgsql security definer set search_path='' as $$declare b public.battles;s public.battle_combat_state;p public.battle_participants;opponent uuid;amount integer;repeat_count integer;eligible boolean;win boolean;begin
 select * into b from public.battles where id=target_battle for update;select * into s from public.battle_combat_state where battle_id=b.id;
 if b.status<>'active' or s.phase<>'finished' then return;end if;
 -- Rewards depend on actual play and account age, never spectators or popularity.
 eligible:=s.turn>=5 and not exists(select 1 from public.battle_participants p join auth.users u on u.id=p.user_id where p.battle_id=b.id and u.created_at>now()-interval '7 days');
 for p in select * from public.battle_participants where battle_id=b.id order by user_id loop perform pg_advisory_xact_lock(hashtextextended('kaidra:xp:'||p.user_id::text,0));end loop;
 for p in select * from public.battle_participants where battle_id=b.id loop
 select user_id into opponent from public.battle_participants where battle_id=b.id and team<>p.team order by user_id limit 1;win:=s.winning_team=p.team;
 select count(*) into repeat_count from public.battle_rewards where user_id=p.user_id and opponent_id=opponent and created_at>now()-interval '1 day';
 amount:=case when eligible and s.winning_team is not null then least(case when win then case when repeat_count=0 then 25 when repeat_count=1 then 20 when repeat_count=2 then 10 else 0 end else case when repeat_count<3 then 5 else 0 end end,greatest(0,50-coalesce((select sum(xp) from public.battle_rewards where user_id=p.user_id and created_at>=date_trunc('day',now())),0)::integer)) else 0 end;
 insert into public.battle_rewards values(b.id,p.user_id,opponent,amount,now()) on conflict do nothing;
 insert into public.battle_stats(user_id,xp,battles,wins,losses,draws,streak) values(p.user_id,amount,1,case when win then 1 else 0 end,case when s.winning_team is not null and not win then 1 else 0 end,case when s.winning_team is null then 1 else 0 end,case when win then 1 else 0 end)
 on conflict(user_id) do update set xp=battle_stats.xp+excluded.xp,battles=battle_stats.battles+1,wins=battle_stats.wins+excluded.wins,losses=battle_stats.losses+excluded.losses,draws=battle_stats.draws+excluded.draws,streak=case when win then battle_stats.streak+1 else 0 end,updated_at=now();
 end loop;
 update public.battles set status='resolved',winner_id=case s.winning_team when 1 then b.challenger_id when 2 then b.challenged_id else null end,outcome=case when s.winning_team is null then 'draw' else 'combat' end,resolved_at=now() where id=b.id;
end $$;
-- A service-only transaction atomically commits the trusted engine's result.
create function public.kaidra_combat_commit(target_battle uuid,actor uuid,request_id uuid,expected_revision integer,intent jsonb,result jsonb) returns boolean language plpgsql security definer set search_path='' as $$declare s public.battle_combat_state;existing public.battle_events;f jsonb;n integer;begin
 select * into s from public.battle_combat_state where battle_id=target_battle for update;
 select * into existing from public.battle_events where battle_id=target_battle and battle_events.request_id=kaidra_combat_commit.request_id;
 if existing.request_id is not null then if existing.actor<>actor or existing.payload->'intent' is distinct from intent then raise exception 'Idempotency conflict';end if;return true;end if;
 if s.phase<>'playing' or s.revision<>expected_revision then return false;end if;
 if intent->>'action'<>'surrender' and actor<>s.active_id then raise exception 'Turn ownership required';end if;
 if not exists(select 1 from public.battle_participants where battle_id=target_battle and user_id=actor and hp>0) then raise exception 'Fighter unavailable';end if;
 if octet_length(result::text)>100000 or jsonb_array_length(result#>'{state,fighters}')<>(select count(*) from public.battle_participants where battle_id=target_battle) or(result#>>'{state,revision}')::integer<>s.revision+1 then raise exception 'Invalid engine result';end if;
 for f in select value from jsonb_array_elements(result#>'{state,fighters}') loop
 if not exists(select 1 from public.battle_participants where battle_id=target_battle and user_id=(f->>'user_id')::uuid and team=(f->>'team')::integer and class_id=f->>'class_id' and max_hp=(f->>'max_hp')::integer and turn_order=(f->>'turn_order')::integer and turns<=(f->>'turns')::integer) then raise exception 'Invalid participant snapshot';end if;
 update public.battle_participants set hp=(f->>'hp')::integer,resource=(f->>'resource')::integer,turns=(f->>'turns')::integer,timeouts=(f->>'timeouts')::integer where battle_id=target_battle and user_id=(f->>'user_id')::uuid;
 end loop;
 delete from public.battle_status_effects where battle_id=target_battle;
 insert into public.battle_status_effects select target_battle,id,kind,source::uuid,target::uuid,amount,expires,charges,data from jsonb_to_recordset(result#>'{state,effects}') x(id text,kind text,source text,target text,amount integer,expires integer,charges integer,data jsonb);
 delete from public.battle_cooldowns where battle_id=target_battle;
 insert into public.battle_cooldowns select target_battle,user_id::uuid,ability_id,ready_turn from jsonb_to_recordset(result#>'{state,cooldowns}') x(user_id text,ability_id text,ready_turn integer);
 update public.battle_combat_state set phase=result#>>'{state,phase}',active_id=nullif(result#>>'{state,active_id}','')::uuid,turn=(result#>>'{state,turn}')::integer,round=(result#>>'{state,round}')::integer,revision=s.revision+1,deadline=(result#>>'{state,deadline}')::timestamptz,winning_team=(result#>>'{state,winning_team}')::integer where battle_id=target_battle;
 insert into public.battle_events values(target_battle,s.revision+1,request_id,actor,intent->>'ability',nullif(intent->>'target','')::uuid,jsonb_build_object('intent',intent,'events',result->'events'),now());
 perform public.kaidra_combat_finish(target_battle);return true;
end $$;
create function public.kaidra_combat_state(target_battle uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare b public.battles;s public.battle_combat_state;begin
 select * into b from public.battles where id=target_battle;if not public.kaidra_battle_visible(b.id) then raise exception 'Conversation membership required';end if;
 select * into s from public.battle_combat_state where battle_id=b.id;
 return jsonb_build_object('battle',to_jsonb(b),'combat',to_jsonb(s)-'seed','server_now',now(),'fighters',coalesce((select jsonb_agg(to_jsonb(p)||jsonb_build_object('name',coalesce(u.display_name,u.username),'avatar_url',u.avatar_url,'identity',public.kaidra_battle_identity(p.user_id)) order by p.turn_order,p.team,p.user_id) from public.battle_participants p join public.profiles u on u.id=p.user_id where p.battle_id=b.id),'[]'::jsonb),'effects',coalesce((select jsonb_agg(to_jsonb(e)) from public.battle_status_effects e where battle_id=b.id),'[]'::jsonb),'cooldowns',coalesce((select jsonb_agg(to_jsonb(c)) from public.battle_cooldowns c where battle_id=b.id),'[]'::jsonb),'events',coalesce((select jsonb_agg(to_jsonb(e) order by sequence) from(select * from public.battle_events where battle_id=b.id order by sequence desc limit 30) e),'[]'::jsonb),'predictions',coalesce((select jsonb_agg(jsonb_build_object('side',side,'count',n)) from(select side,count(*) n from public.battle_votes where battle_id=b.id group by side) v),'[]'::jsonb),'own_prediction',(select side from public.battle_votes where battle_id=b.id and user_id=auth.uid()),'own_rewards',coalesce((select jsonb_agg(to_jsonb(r)) from public.battle_rewards r where battle_id=b.id and user_id=auth.uid()),'[]'::jsonb),'own_stats',(select to_jsonb(p) from public.battle_stats p where p.user_id=auth.uid()),'abilities',(select c.ability_metadata from public.battle_participants p join public.battle_classes c on c.id=p.class_id where p.battle_id=b.id and p.user_id=auth.uid()));
end $$;
create function public.kaidra_combat_history() returns jsonb language sql stable security definer set search_path='' as $$select coalesce(jsonb_agg(row),'[]'::jsonb) from(select to_jsonb(b)||jsonb_build_object('fighters',(select jsonb_agg(jsonb_build_object('id',p.user_id,'name',coalesce(u.display_name,u.username),'class_id',coalesce(p.class_id,i.class_id),'team',p.team)) from public.battle_participants p join public.profiles u on u.id=p.user_id left join public.battle_identities i on i.user_id=p.user_id where p.battle_id=b.id),'own_reward',(select xp from public.battle_rewards where battle_id=b.id and user_id=auth.uid())) row from public.battles b join public.battle_participants own on own.battle_id=b.id and own.user_id=auth.uid() where public.kaidra_battle_visible(b.id) order by b.created_at desc limit 50) q;$$;
-- Messaging uses the preserved notification/event infrastructure, with accurate combat labels.
create or replace function public.kaidra_battle_event() returns trigger language plpgsql security definer set search_path='' as $$declare label text;uid uuid;begin
 if tg_op='INSERT' or new.status is distinct from old.status then
 label:=case new.status when 'pending' then 'A friendly challenge was issued' when 'active' then case when new.combat_version=1 then 'Combat has begun' else 'Debate started' end when 'resolved' then case when new.combat_version=1 then case when new.winner_id is null then 'The battle ended in a draw' else 'The battle has a winner' end else 'The debate has ended' end when 'declined' then 'Challenge declined' when 'cancelled' then 'Challenge cancelled' else 'Challenge expired' end;
 insert into public.messages(conversation_id,sender_id,content,message_type,event_data) values(new.conversation_id,coalesce(auth.uid(),new.challenger_id),label||' · '||new.topic,'system',jsonb_build_object('kind','battle','battle_id',new.id,'status',new.status));
 for uid in select user_id from public.conversation_participants where conversation_id=new.conversation_id loop perform public.kaidra_social_signal(uid);end loop;
 if new.status='pending' then perform public.kaidra_notify(new.challenged_id,'battle','battle:'||new.id||':pending','You’ve been challenged',new.topic,'inbox/'||new.conversation_id,jsonb_build_object('battle_id',new.id));
 elsif new.status in('active','declined','resolved') then for uid in select user_id from public.battle_participants where battle_id=new.id union select new.challenger_id union select new.challenged_id loop perform public.kaidra_notify(uid,'battle','battle:'||new.id||':'||new.status,label,new.topic,'inbox/'||new.conversation_id,jsonb_build_object('battle_id',new.id));end loop;end if;
 end if;return null;
end $$;
do $$declare fn record;t text;begin for fn in select oid::regprocedure signature,proname from pg_proc where pronamespace='public'::regnamespace and proname in('kaidra_combat_prepare','kaidra_combat_start','kaidra_combat_finish','kaidra_combat_commit','kaidra_combat_state','kaidra_combat_history') loop execute format('revoke all on function %s from public,anon,authenticated',fn.signature);execute format('grant execute on function %s to %I',fn.signature,case when fn.proname in('kaidra_combat_state','kaidra_combat_history') then 'authenticated' else 'service_role' end);end loop;
 foreach t in array array['battle_participants','battle_status_effects','battle_cooldowns','battle_events'] loop if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then execute format('alter publication supabase_realtime add table public.%I',t);end if;end loop;
end $$;
update public.battle_classes set base_hp=120,starting_resource=100,initiative=4,resource_name='Stamina',ability_metadata='[{"id":"slash","name":"Slash","kind":"attack","target":"enemy","cost":0,"cooldown":0,"description":"Reliable physical pressure.","min":16,"max":20},{"id":"guard_break","name":"Guard Break","kind":"pierce","target":"enemy","cost":20,"cooldown":2,"description":"Break half of shields and guarding.","min":24,"max":28},{"id":"parry","name":"Parry","kind":"counter","target":"self","cost":15,"cooldown":2,"description":"Reduce one hit by 50% and retaliate for 8.","amount":8,"duration":2},{"id":"battle_cry","name":"Battle Cry","kind":"buff","target":"self","cost":25,"cooldown":3,"description":"Add 6 damage to attacks for 3 own turns.","amount":6,"duration":3},{"id":"last_stand","name":"Last Stand","kind":"attack","target":"enemy","cost":30,"cooldown":4,"description":"Heavy pressure when your HP is at most 35%.","min":30,"max":38,"condition":"low_hp"}]'::jsonb where id='warrior';
update public.battle_classes set base_hp=100,starting_resource=100,initiative=3,resource_name='Mana',ability_metadata='[{"id":"arcane_bolt","name":"Arcane Bolt","kind":"attack","target":"enemy","cost":10,"cooldown":0,"description":"A reliable magical attack.","min":14,"max":18},{"id":"hex","name":"Hex","kind":"weaken","target":"enemy","cost":20,"cooldown":2,"description":"Reduce outgoing damage by 6 for 2 own turns.","amount":6,"duration":2},{"id":"barrier","name":"Barrier","kind":"shield","target":"self","cost":25,"cooldown":2,"description":"Absorb 28 damage for up to 3 own turns.","amount":28,"duration":3},{"id":"mana_focus","name":"Mana Focus","kind":"focus","target":"self","cost":0,"cooldown":2,"description":"Recover 35 mana instead of attacking.","amount":35},{"id":"arcane_burst","name":"Arcane Burst","kind":"cast","target":"enemy","cost":40,"cooldown":3,"description":"Telegraph a spell. 32–40 damage resolves before your next turn. Disruption can interrupt it.","min":32,"max":40,"duration":1}]'::jsonb where id='wizard';
update public.battle_classes set base_hp=100,starting_resource=100,initiative=8,resource_name='Energy',ability_metadata='[{"id":"shadow_strike","name":"Shadow Strike","kind":"attack","target":"enemy","cost":10,"cooldown":0,"description":"Fast, precise damage.","min":18,"max":22},{"id":"smoke_step","name":"Smoke Step","kind":"evade","target":"self","cost":20,"cooldown":2,"description":"Reduce the next incoming attack by 70%.","amount":70,"duration":2},{"id":"kunai_rush","name":"Kunai Rush","kind":"multi","target":"enemy","cost":25,"cooldown":2,"description":"Three hits. Shields absorb each hit.","min":7,"max":8,"hits":3},{"id":"afterimage","name":"Afterimage","kind":"evade","target":"self","cost":30,"cooldown":3,"description":"Reduce the next two incoming hits by 55%.","amount":55,"hits":2,"duration":2},{"id":"execution","name":"Execution","kind":"execute","target":"enemy","cost":30,"cooldown":3,"description":"18–22 damage; adds 14 against a target below 35% HP.","min":18,"max":22,"amount":14}]'::jsonb where id='ninja';
update public.battle_classes set base_hp=125,starting_resource=100,initiative=2,resource_name='Guard',ability_metadata='[{"id":"shield_bash","name":"Shield Bash","kind":"interrupt","target":"enemy","cost":10,"cooldown":1,"description":"Damage and interrupt a charging spell.","min":12,"max":16},{"id":"fortify","name":"Fortify","kind":"guard","target":"self","cost":20,"cooldown":2,"description":"Reduce incoming damage by 45% for 2 own turns.","amount":45,"duration":2},{"id":"perfect_guard","name":"Perfect Guard","kind":"guard_once","target":"self","cost":30,"cooldown":3,"description":"Reduce one incoming attack by 80%.","amount":80,"duration":2},{"id":"counter","name":"Counter","kind":"counter","target":"self","cost":20,"cooldown":2,"description":"Reduce one attack by 50% and retaliate for 14.","amount":14,"duration":2},{"id":"unbreakable","name":"Unbreakable","kind":"shield","target":"self","cost":40,"cooldown":4,"description":"Absorb 40 damage for up to 3 own turns.","amount":40,"duration":3},{"id":"protect","name":"Protect","kind":"protect","target":"ally","cost":25,"cooldown":2,"description":"Intercept 60% of attacks aimed at an ally for 2 own turns. Intercepted damage uses your defenses.","amount":60,"duration":2}]'::jsonb where id='guardian';
update public.battle_classes set base_hp=105,starting_resource=100,initiative=6,resource_name='Momentum',ability_metadata='[{"id":"cheap_shot","name":"Cheap Shot","kind":"exploit","target":"enemy","cost":0,"cooldown":0,"description":"14–18 damage. Add 10 if the target is marked or vulnerable.","min":14,"max":18,"amount":10},{"id":"feint","name":"Feint","kind":"vulnerable","target":"enemy","cost":15,"cooldown":2,"description":"Remove guarding and create an opening: +6 incoming damage for 2 own turns.","amount":6,"duration":2},{"id":"sabotage","name":"Sabotage","kind":"sabotage","target":"enemy","cost":20,"cooldown":2,"description":"Steal up to 20 resource and weaken attacks by 4 for 2 own turns.","amount":20,"duration":2},{"id":"mark","name":"Mark","kind":"marked","target":"enemy","cost":15,"cooldown":2,"description":"Expose an opening: +5 incoming damage for 3 own turns.","amount":5,"duration":3},{"id":"all_in","name":"All In","kind":"reckless","target":"enemy","cost":35,"cooldown":3,"description":"34–44 damage. You lose 12 HP and become vulnerable.","min":34,"max":44,"amount":12,"duration":2}]'::jsonb where id='rogue';
update public.battle_classes set base_hp=105,starting_resource=100,initiative=3,resource_name='Spirit',ability_metadata='[{"id":"radiant_strike","name":"Radiant Strike","kind":"attack","target":"enemy","cost":0,"cooldown":0,"description":"Reliable light damage.","min":16,"max":20},{"id":"restoration","name":"Restoration","kind":"heal","target":"ally","cost":30,"cooldown":3,"description":"Restore 26 HP. Late-battle healing is reduced.","amount":26},{"id":"purify","name":"Purify","kind":"purify","target":"ally","cost":20,"cooldown":2,"description":"Remove negative statuses and restore 8 HP.","amount":8},{"id":"sacred_shield","name":"Sacred Shield","kind":"shield","target":"ally","cost":25,"cooldown":2,"description":"Absorb 28 damage for up to 3 own turns.","amount":28,"duration":3},{"id":"regeneration","name":"Regeneration","kind":"regen","target":"ally","cost":25,"cooldown":4,"description":"Restore 8 HP at the start of 3 own turns.","amount":8,"duration":3},{"id":"judgement","name":"Judgement","kind":"attack","target":"enemy","cost":25,"cooldown":3,"description":"A decisive light attack.","min":28,"max":34}]'::jsonb where id='healer';
update public.battle_classes set base_hp=105,starting_resource=100,initiative=5,resource_name='Focus',ability_metadata='[{"id":"quick_shot","name":"Quick Shot","kind":"attack","target":"enemy","cost":0,"cooldown":0,"description":"A reliable ranged shot.","min":18,"max":22},{"id":"mark_target","name":"Mark Target","kind":"marked","target":"enemy","cost":15,"cooldown":2,"description":"Expose a precise opening: +6 incoming damage for 3 own turns.","amount":6,"duration":3},{"id":"piercing_shot","name":"Piercing Shot","kind":"pierce","target":"enemy","cost":25,"cooldown":2,"description":"Bypass half of shielding and guarding.","min":26,"max":30},{"id":"trap","name":"Trap","kind":"trap","target":"enemy","cost":20,"cooldown":3,"description":"The next offensive action triggers 10 damage.","amount":10,"duration":3},{"id":"reposition","name":"Reposition","kind":"guard","target":"self","cost":20,"cooldown":2,"description":"Create distance: reduce damage by 35% for 2 own turns.","amount":35,"duration":2},{"id":"volley","name":"Volley","kind":"attack","target":"all_enemies","cost":35,"cooldown":3,"description":"A measured volley against every living enemy.","min":15,"max":19}]'::jsonb where id='ranger';
update public.battle_classes set base_hp=125,starting_resource=40,initiative=4,resource_name='Rage',ability_metadata='[{"id":"blood_strike","name":"Blood Strike","kind":"blood","target":"enemy","cost":0,"cooldown":0,"description":"22–26 damage, at a cost of 6 HP. Low HP adds up to 6 pressure.","min":22,"max":26,"amount":6},{"id":"reckless_assault","name":"Reckless Assault","kind":"reckless","target":"enemy","cost":25,"cooldown":2,"description":"32–40 damage. Lose 12 HP and become vulnerable.","min":32,"max":40,"amount":12,"duration":2},{"id":"frenzy","name":"Frenzy","kind":"frenzy","target":"self","cost":25,"cooldown":3,"description":"Add 8 outgoing damage but take 6 extra damage for 3 own turns.","amount":8,"duration":3},{"id":"rage","name":"Rage","kind":"rage","target":"self","cost":0,"cooldown":2,"description":"Gain 40 rage at a cost of 6 HP.","amount":40},{"id":"deaths_door","name":"Death’s Door","kind":"attack","target":"enemy","cost":40,"cooldown":4,"description":"40–48 damage, usable at most 35% HP. Remaining at low HP is dangerous.","min":40,"max":48,"condition":"low_hp"}]'::jsonb where id='berserker';
CREATE OR REPLACE FUNCTION public.kaidra_battle_create_internal(target_conversation uuid, target_user uuid, topic text, stance text, context jsonb DEFAULT '{}'::jsonb, request_id uuid DEFAULT gen_random_uuid())
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare expired record; m public.messages; entry text; side_a text; side_b text;begin
 perform 1 from public.conversations where id=target_conversation for share;
 if not public.kaidra_can_send_message(target_conversation) or not public.kaidra_pair_allowed(auth.uid(),target_user) or (not public.kaidra_friends(auth.uid(),target_user) and not exists(select 1 from public.conversations where id=target_conversation and is_group)) or not exists(select 1 from public.conversation_participants where conversation_id=target_conversation and user_id=target_user) then raise exception 'Challenge a friend in this conversation';end if;
 if exists(select 1 from public.battles where id=request_id and challenger_id=auth.uid() and challenged_id=target_user and conversation_id=target_conversation) then return request_id;end if;
 if context is null or jsonb_typeof(context)<>'object' or octet_length(context::text)>=12000 then raise exception 'Invalid challenge context';end if;
 entry:=coalesce(context->>'entry_type','opinion');
 if entry='discussion' then
 select * into m from public.messages where id=(context->>'discussion_message_id')::uuid for update;
 if m.conversation_id is distinct from target_conversation or m.message_type<>'discussion' or m.deleted_at is not null then raise exception 'Choose an accessible discussion';end if;
 side_a:=case when auth.uid()=m.sender_id then 'agree' else (select position from public.discussion_positions where discussion_message_id=m.id and user_id=auth.uid()) end;
 side_b:=case when target_user=m.sender_id then 'agree' else (select position from public.discussion_positions where discussion_message_id=m.id and user_id=target_user) end;
 if side_a is null or side_b is null or side_a=side_b then raise exception 'Choose someone on the opposing side';end if;
 topic:=left(m.content,240);stance:=side_a;context:=jsonb_build_object('entry_type','discussion','discussion_message_id',m.id,'statement',m.content,'opponent_position',side_b);
 elsif entry='direct' then
 if length(coalesce(topic,''))>240 then raise exception 'Keep challenge text under 240 characters';end if;
 context:=jsonb_build_object('entry_type','direct','flavour_text',coalesce(topic,''));topic:='Friendly battle';stance:=null;
 elsif entry='opinion' then
 if topic is null or length(trim(topic)) not between 1 and 240 or stance is null or length(trim(stance)) not between 1 and 1200 then raise exception 'Add a topic and your stance';end if;
 else raise exception 'Unknown challenge entry';end if;
 perform pg_advisory_xact_lock(hashtextextended('kaidra:battle:'||least(auth.uid(),target_user)::text||greatest(auth.uid(),target_user)::text,0));
 update public.battles set status='expired' where combat_version=0 and status='active' and type='direct' and ends_at<=now() and least(challenger_id,challenged_id)=least(auth.uid(),target_user) and greatest(challenger_id,challenged_id)=greatest(auth.uid(),target_user);
 for expired in select id from public.battles where combat_version=0 and type<>'direct' and status='active' and ends_at<=now() and least(challenger_id,challenged_id)=least(auth.uid(),target_user) and greatest(challenger_id,challenged_id)=greatest(auth.uid(),target_user) loop perform public.kaidra_battle_action(expired.id,'finish');end loop;
 update public.battles set status='expired' where status='pending' and created_at<now()-interval '1 day' and auth.uid() in(challenger_id,challenged_id);
 if (select count(*) from public.battle_attempts where challenger_id=auth.uid() and created_at>now()-interval '1 day')>=5 then raise exception 'Give this matchup a break. Try another friend later';end if;
 insert into public.battles(id,conversation_id,challenger_id,challenged_id,topic,challenger_position,context,type,discussion_message_id,flavour_text) values(request_id,target_conversation,auth.uid(),target_user,trim(topic),trim(stance),context,entry,m.id,case when entry='direct' then context->>'flavour_text' end);return request_id;
end $function$;

notify pgrst,'reload schema';
commit;
